// src/data/textbooks.ts
import { Textbook } from "@/types/types";

export const textbookData: Textbook[] = [
    {
      id: 1,
      title: "Calculus, Vol. 1: One Variable Calculus, with an Introduction to Linear Algebra",
      author: "Tom M. Apostol",
      edition: "Second Edition",
      year: "1967",
      chapters: [
        {
          id: 13,
          title: "Chapter 13: Applications of Vector Algebra to Analytic Geometry",
          description: "Applications of vector algebra to the study of lines, planes, and conic sections.",
          problemSets: [
            {
              id: 25,
              title: "13.25 Miscellaneous exercises on conic sections",
              description: "A review section combining the material on conic sections with material from previous chapters",
              problems: [
                {
                  id: 1,
                  number: "13.25.1",
                  content: `Show that the area of the region bounded by the ellipse $\\frac{x^{2}}{a^{2}} + \\frac{y^{2}}{b^{2}} = 1$ is $ab$ times the area of a circle with radius 1. \n\nNote: This statement can be proved from general properties of the integral, without performing any integrations.`,
                  hint: "Use Theorem 1.19 (Expansion or Contraction of the Interval of Integration): If $f$ is integrable on $[a, b]$, then for every real $k\\neq0$ we have $$\\int_{a}^{b} f(x)\\ dx = \\frac{1}{k}\\int_{ka}^{kb} f\\left(\\frac{x}{k}\\right)\\ dx$$",
                  solution: "We can express a circle of radius 1 centered at the origin as an ellipse with $a = b = 1$. In other words the standard form of a circle is $x^{2} + y^{2} = 1$. Expressing this as a function of $x$ gives us the graph of the upper semicircle $y = f(x) = \\sqrt{1 - x^{2}}$. Taking twice the area under the curve from $x = -1$ to $x = 1$ we get $$A_{circle} = 2\\int_{-1}^{1}\\sqrt{1 - x^{2}} \\ dx$$Doing the same for the ellipse with equation $\\frac{x^{2}}{a^{2}} + \\frac{y^{2}}{b^{2}} = 1$ from its left to its right vertices, we see that its area is $$A_{ellipse} = 2|b|\\int_{-a}^{a}\\sqrt{1 - \\left(\\frac{x}{a}\\right)^2} \\ dx$$But we know from Theorem 1.19 (Expansion or Contraction of the Interval of Integration) that this integral is equal to $$2ab\\int_{-1}^{1}\\sqrt{1 - x^{2}} \\ dx = abA_{circle} \\quad \\blacksquare$$",
                  date: "11-25-2024"
                },
                {
                  id: 2,
                  number: "13.25.2",
                  content: `(a) Show that the volume of the solid of revolution generated by rotating the ellipse $$\\frac{x^{2}}{a^{2}} + \\frac{y^{2}}{b^{2}} = 1$$about its major axis is $ab^{2}$ times the volume of a unit sphere. \n\nNote: This statement can be proved from general properties of the integral, without performing any integrations.\n\n(b) What is the result if it is rotated about its minor axis?`,
                  hint: "The volume of a solid of revolution with cross sections cut along the $x$ axis is $$\\int_{a}^{b}\\pi f^{2}(x)  \\ dx$$\nTo show how the integral scales, use Theorem 1.19 (Expansion or Contraction of the Interval of Integration): If $f$ is integrable on $[a, b]$, then for every real $k\\neq0$ we have $$\\int_{a}^{b} f(x)\\ dx = \\frac{1}{k}\\int_{ka}^{kb} f\\left(\\frac{x}{k}\\right)\\ dx$$",
                  solution: "(a) The volume of a unit sphere can be expressed as the integral $$V_{c} = \\pi\\int_{-1}^{1} (1 - x^{2})\\ dx$$As we saw in problem 1, we can express the upper half of the ellipse defined by the equation $\\frac{x^{2}}{a^{2}} + \\frac{y^{2}}{b^{2}} = 1$ as $y = f(x) = |b|\\sqrt{1 - \\left(\\frac{x}{a}\\right)^{2}}$. Its volume of revolution about the $x$ axis is $$V_{e} = b^{2}\\pi\\int_{-a}^{a} 1 - \\left(\\frac{x}{a}\\right)^{2}\\ dx$$But from Theorem 1.19 we know that this integral is equal to $$ab^{2}\\pi\\int_{-1}^{1} (1 - x^{2})\\ dx$$Which is $ab^{2}$ times the volume of a unit sphere. $\\blacksquare$\n\n(b) The solid obtained by revolving the ellipse around its minor axis (in this case, the $y$ axis) would have a volume $a^{2}b$ times the volume of a unit sphere. The positive half-ellipse can be written as a function of $y$ as follows: $$x = f(y) = |a|\\sqrt{1 - \\left(\\frac{y}{b}\\right)^{2}}$$Its volume of revolution is then $$a^{2}\\pi\\int_{-b}^{b} 1 - \\left(\\frac{y}{b}\\right)^{2}\\ dy$$so it follows that its volume is $a^{2}b$ times that of the unit sphere. $\\blacksquare$",
                  date: "11-25-2024"
                },
              ]
            }
          ]
        },
      ]
    },
    // {
    //   id: 2,
    //   title: "Linear Algebra Done Right",
    //   author: "Sheldon Axler",
    //   edition: "Third Edition",
    //   year: "2015",
    //   chapters: []  // We can fill this in later
    // },
    // Add more textbooks as needed
  ];