// src/data/textbooks.ts
import { Textbook } from "@/types/types";

export const textbookData: Textbook[] = [
    {
      id: 1,
      title: "Calculus, Vol. 1: One Variable Calculus, with an Introduction to Linear Algebra",
      author: "Tom M. Apostol",
      edition: "Second Edition",
      year: "1967",
      chapters: [
        {
          id: 13,
          title: "Chapter 13: Applications of Vector Algebra to Analytic Geometry",
          description: "Applications of vector algebra to the study of lines, planes, and conic sections.",
          problemSets: [
            {
              id: 25,
              title: "13.25 Miscellaneous exercises on conic sections",
              description: "A review section combining the material on conic sections with material from previous chapters",
              problems: [
                {
                  id: 1,
                  number: "13.25.1",
                  content: `Show that the area of the region bounded by the ellipse $\\frac{x^{2}}{a^{2}} + \\frac{y^{2}}{b^{2}} = 1$ is $ab$ times the area of a circle with radius 1. \n\nNote: This statement can be proved from general properties of the integral, without performing any integrations.`,
                  hint: "Use Theorem 1.19 (Expansion or Contraction of the Interval of Integration): If $f$ is integrable on $[a, b]$, then for every real $k\\neq0$ we have $$\\int_{a}^{b} f(x)\\ dx = \\frac{1}{k}\\int_{ka}^{kb} f\\left(\\frac{x}{k}\\right)\\ dx$$",
                  solution: "We can express a circle of radius 1 centered at the origin as an ellipse with $a = b = 1$. In other words the standard form of a circle is $x^{2} + y^{2} = 1$. Expressing this as a function of $x$ gives us the graph of the upper semicircle $y = f(x) = \\sqrt{1 - x^{2}}$. Taking twice the area under the curve from $x = -1$ to $x = 1$ we get $$A_{circle} = 2\\int_{-1}^{1}\\sqrt{1 - x^{2}} \\ dx$$Doing the same for the ellipse with equation $\\frac{x^{2}}{a^{2}} + \\frac{y^{2}}{b^{2}} = 1$ from its left to its right vertices, we see that its area is $$A_{ellipse} = 2|b|\\int_{-a}^{a}\\sqrt{1 - \\left(\\frac{x}{a}\\right)^2} \\ dx$$But we know from Theorem 1.19 (Expansion or Contraction of the Interval of Integration) that this integral is equal to $$2ab\\int_{-1}^{1}\\sqrt{1 - x^{2}} \\ dx = abA_{circle} \\quad \\blacksquare$$",
                  date: "2024-11-25"
                },
                {
                  id: 2,
                  number: "13.25.2",
                  content: `(a) Show that the volume of the solid of revolution generated by rotating the ellipse $$\\frac{x^{2}}{a^{2}} + \\frac{y^{2}}{b^{2}} = 1$$about its major axis is $ab^{2}$ times the volume of a unit sphere. \n\nNote: This statement can be proved from general properties of the integral, without performing any integrations.\n\n(b) What is the result if it is rotated about its minor axis?`,
                  hint: "The volume of a solid of revolution with cross sections cut along the $x$ axis is $$\\int_{a}^{b}\\pi f^{2}(x)  \\ dx$$\nTo show how the integral scales, use Theorem 1.19 (Expansion or Contraction of the Interval of Integration): If $f$ is integrable on $[a, b]$, then for every real $k\\neq0$ we have $$\\int_{a}^{b} f(x)\\ dx = \\frac{1}{k}\\int_{ka}^{kb} f\\left(\\frac{x}{k}\\right)\\ dx$$",
                  solution: "(a) The volume of a unit sphere can be expressed as the integral $$V_{c} = \\pi\\int_{-1}^{1} (1 - x^{2})\\ dx$$As we saw in problem 1, we can express the upper half of the ellipse defined by the equation $\\frac{x^{2}}{a^{2}} + \\frac{y^{2}}{b^{2}} = 1$ as $y = f(x) = |b|\\sqrt{1 - \\left(\\frac{x}{a}\\right)^{2}}$. Its volume of revolution about the $x$ axis is $$V_{e} = b^{2}\\pi\\int_{-a}^{a} 1 - \\left(\\frac{x}{a}\\right)^{2}\\ dx$$But from Theorem 1.19 we know that this integral is equal to $$ab^{2}\\pi\\int_{-1}^{1} (1 - x^{2})\\ dx$$Which is $ab^{2}$ times the volume of a unit sphere. $\\blacksquare$\n\n(b) The solid obtained by revolving the ellipse around its minor axis (in this case, the $y$ axis) would have a volume $a^{2}b$ times the volume of a unit sphere. The positive half-ellipse can be written as a function of $y$ as follows: $$x = f(y) = |a|\\sqrt{1 - \\left(\\frac{y}{b}\\right)^{2}}$$Its volume of revolution is then $$a^{2}\\pi\\int_{-b}^{b} 1 - \\left(\\frac{y}{b}\\right)^{2}\\ dy$$so it follows that its volume is $a^{2}b$ times that of the unit sphere. $\\blacksquare$",
                  date: "2024-11-25"
                },
                {
                  id: 3,
                  number: "13.25.3",
                  content: "Find all positive numbers $A$ and $B$, $A\\ > B$, such that the area of the region enclosed by the ellipse $Ax^{2} + By^{2} = 3$ is equal to the area of the region enclosed by the ellipse $$(A + B)x^{2} + (A - B)y^{2} = 3$$",
                  hint: "Rewrite the equations $Ax^{2} + By^{2} = 3$ and $(A + B)x^{2} + (A - B)y^{2} = 3$ as $$\\frac{x^{2}}{a_0^{2}} + \\frac{y^{2}}{b_0^{2}} = 1; \\quad \\frac{x^{2}}{a_1^{2}} + \\frac{y^{2}}{b_1^{2}} = 1$$respectively, where $$a_{0}^{2} = \\frac{3}{A}, \\ b_{0}^{2} = \\frac{3}{B}; \\quad a_{1}^{2} = \\frac{3}{(A + B)}, \\ b_{1}^{2} = \\frac{3}{(A-B)}$$then, use the result from problem (1) to find the areas bounded by the two ellipses.",
                  solution: "We know from the proof of problem (1) that an ellipse with the standard form $$\\frac{x^{2}}{a^{2}} + \\frac{y^{2}}{b^{2}} = 1$$has an area $ab$ times that of a circle with radius 1. As such, the area of the region enclosed by the ellipse $Ax^{2} + By^{2} = 3$ is $\\frac{3}{\\sqrt{AB}}$ and the area of the ellipse enclosed by $$(A + B)x^{2} + (A - B)y^{2} = 3$$ is $\\frac{3}{\\sqrt{(A+B)(A-B)}}$. Setting these two areas equal to one-another, we see $$\\frac{3}{\\sqrt{AB}} = \\frac{3}{\\sqrt{(A+B)(A-B)}} \\quad (\\text{where} \\ AB>0,\\ A^{2} - B^{2}> 0)$$We can write this in the equivalent form $$A^{2} - AB - B^{2} = 0 \\quad (\\text{where} \\ AB>0, \\ A^{2} - B^{2}> 0)$$Solving this quadratic equation with $a = 1, b = -B, c = -B^{2}$ we find that $$\\displaylines{A &= \\frac{-b \\pm \\sqrt{b^{2} - 4ac}}{2a} \\\\&=\\frac{(1 \\pm \\sqrt{5})B}{2}}$$But we know that $A \\ > B, \\ AB \\ > 0, \\ A^{2} - B^{2} > 0$, thus $$A = \\frac{(1 + \\sqrt{5})B}{2} \\quad (\\text{where}\\ B > 0)\\quad \\blacksquare$$", 
                  date: "2024-11-28"
                },
                {
                  id: 4,
                  number: "13.25.4",
                  content: "A parabolic arch has base of length $b$ and height $h$. Determine the area of the region bounded by the arch and the base.",
                  hint: "Recall that the equation for a parabola opening downwards with vertex $(0, h)$ is $$x^{2} = 4c(y - h)\\quad (\\text{where}\\ c < 0)$$If we place its $x$ intercepts (where $y = 0$) at $\\frac{-b}{2}$ and $\\frac{b}{2}$, then its base will then be of length $b$. Setting $x = \\frac{b}{2}$ and solving for $c$ we get $c = \\frac{-b^{2}}{16h}$.",
                  solution: "Let the equation for the parabola with vertex $(0, h)$ and base of length $b$ be the function of $x$: $$y = f(x) = \\frac{x^{2}}{4c} + h\\quad (\\text{where}\\ c = \\frac{-b^{2}}{16h})$$Integrating from $x=\\frac{-b}{2}$ to $x=\\frac{b}{2}$ we get $$\\displaylines{\\int_{-b/2}^{b/2} \\frac{x^{2}}{4c} + h\\ dx &= \\ \\frac{x^{3}}{12c} + hx\\ \\Biggr|_{-b/2}^{b/2} \\\\ &=\\frac{b^{3}}{48c} + hb}$$Substituting $c = \\frac{-b^{2}}{16h}$ we get $$\\displaylines{\\frac{b^{3}}{48c} + hb = \\left(\\frac{16h}{-b^{2}}\\right)\\frac{b^{3}}{48}} + hb \\ = \\frac{2}{3}hb \\quad \\blacksquare$$",
                  date: "2024-12-03"
                },
                {
                  id: 5,
                  number: "13.25.5",
                  content: "The region bounded by the parabola $y^{2} = 8x$ and the line $x = 2$ is rotated about the $x$ axis. Find the volume of the solid of revolution so generated.",
                  hint: "The volume of a solid of revolution with cross sections cut along the $x$ axis is $$\\int_{a}^{b}\\pi f^{2}(x)  \\ dx$$\nBut if we define $y = f(x)$, then $f^{2}(x) = y^{2} = 8x$. We know from the parabola's equation that its vertex is $(0, 0)$, and since the cross sectional region is bound by the vertical line at $x = 2$, our limits of integration must be $a = 0$ and $b = 2$.",
                  solution: "The solid of revolution generated by rotating the above defined cross-sectional area around the $x$ axis is: $$\\displaylines{V = 8\\pi \\int_{0}^{2}x \\ dx \\\\ = 4\\pi x^{2}\\Biggr|_{0}^{2} \\\\ = 16\\pi \\ \\blacksquare}$$",
                  date: "2024-12-03"
                },
                {
                  id: 6,
                  number: "13.25.6",
                  content: "Two parabolas having the equations $y^{2} = 2(x - 1)$ and $y^{2} = 4(x - 2)$ enclose a plane region $R$.\n\t(a) Compute the area of $R$ by integration.\n\t(b) Find the volume of the solid of revolution generated by revolving $R$ about the $x$-axis.\n\t(c) Same as (b), but revolve $R$ about the $y$-axis.",
                  hint: `(a) Rearrange the equations for the parabolas as functions of $y$: $$y^{2} = 2(x - 1) \\quad  \\rightarrow \\quad x = f(y) = \\frac{y^{2}}{2} + 1$$ $$y^{2} = 4(x - 2) \\quad  \\rightarrow \\quad x = f(y) = \\frac{y^{2}}{4} + 2$$\nTo find the limits of integration, find the points at which the two functions intersect, or in other words where: $\\frac{y^{2}}{2} + 1 = \\frac{y^{2}}{4} + 2$.

(b) Take $y$ as a function of $x$ to give $y^{2} = f^{2}(x)$ for each parabola and then use $f^{2}(x)$ to calculate the solid of revolution about the $x$-axis: $$\\int_{a}^{b}\\pi f^{2}(x)  \\ dx$$To find the corresponding limits of integration, note that both the functions for $y^{2}$ are symmetric about the $x$-axis (an exercise for the reader: why is this the case?). Thus, for each integral, we only need to find the points at which the graphs intersect eachother and the $x$-axis.

(c) The cross-sectional areas are now functions of $y$, and thus the solid of revolution about the $y$-axis is $$\\int_{a}^{b}\\pi f^{2}(y)  \\ dy$$To find the limits of integration, find the points at which the two graphs intersect. 
Note: these are the same points of intersection from (a). `,
                  solution: `(a) To find the area of the region $R$ bounded by the graphs of the two functions, first we must find the areas underneath each graph from their points of intersection. $$\\displaylines{A_{0} &= \\int_{-2}^{2} \\frac{y^{2}}{2} + 1 \\ dy\\\\ &= \\frac{y^{3}}{6} + y\\ \\Biggr|_{-2}^{2}\\\\ &= \\frac{80}{12}}$$ $$\\displaylines{A_{1} &= \\int_{-2}^{2} \\frac{y^{2}}{4} + 2 \\ dy\\\\ &= \\frac{y^{3}}{12} + 2y\\ \\Biggr|_{-2}^{2}\\\\ &= \\frac{112}{12}}$$Subtracting $A_{0}$ from $A_{1}$ we get $\\frac{32}{12}$ or $\\frac{8}{3}$ $\\quad \\blacksquare$

(b) To find the volume $V$ of the solid obtained by rotating the region $R$ about the $x$-axis, we find the difference between the volumes obtained by rotating each parabola $y^{2}$ about the $x$-axis. We denote these volumes by $V_{0}$ and $V_{1}$, respectively. Let: $$\\displaylines{V_{0} &= \\pi\\int_{1}^{3}2(x - 1) \\ dx\\\\&=2\\pi(\\frac{x^{2}}{2} - x)\\Biggr|_{1}^{3}\\\\&=4\\pi}$$ $$\\displaylines{V_{1} &= \\pi\\int_{2}^{3}4(x - 2) \\ dx\\\\&=4\\pi(\\frac{x^{2}}{2} - 2x)\\Biggr|_{2}^{3}\\\\&=2\\pi}$$Subtracting the smaller volume $V_{1}$ from the larger $V_{0}$ we get $V = 2\\pi\\quad\\blacksquare$

(c) We know from (a) that the parabolas taken as functions of $y$ are $$x = \\frac{y^{2}}{2} + 1; \\quad x = \\frac{y^{2}}{4} + 2$$The volume of their solids of revolution $V_{0}$ and $V_{1}$ are $$\\displaylines{V_{0}&=\\pi \\int_{-2}^{2}\\frac{y^{4}}{4} + y^{2} + 1 \\ dy\\\\&=\\pi \\left(\\frac{y^{5}}{20} + \\frac{y^{3}}{3} + y\\right) \\Biggr|_{-2}^{2}\\\\&= \\pi \\left(\\frac{16}{5} + \\frac{16}{3} + 4\\right)}$$ $$\\displaylines{V_{1}&=\\pi \\int_{-2}^{2}\\frac{y^{4}}{16} + y^{2} + 4 \\ dy\\\\&=\\pi \\left(\\frac{y^{5}}{80} + \\frac{y^{3}}{3} + 4y\\right) \\Biggr|_{-2}^{2}\\\\&= \\pi \\left(\\frac{4}{5} + \\frac{16}{3} + 16\\right)}$$Subtracting $V_{0}$ from $V_{1}$ we get $V = \\frac{48 \\pi}{5}\\quad\\blacksquare$`,
                  date: "2024-12-03"
                },
                {
                  id: 7,
                  number: "13.25.7",
                  content: "Find a Cartesian equation for the conic section consisting of all points $(x, y)$ whose distance from the point $(0, 2)$ is half the distance from the line $y=8$",
                  hint: `Given a line $L$, a point $F$ not on $L$, and a positive number $e$. Let $d(X,L)$ denote the distance from a point $X$ to $L$. The set of all $X$ satisfying the relation $$\\|X - F\\| = ed(X,L)$$is called a conic section with eccentricity $e$.\n\nIf $N$ is a vector normal to $L$ and if $P$ is any point on $L$, the distance $d(X, L)$ from any point $X$ to $L$ is given by the formula $$d(X, L) = \\frac{\\left|(X - P) \\cdot N\\right|}{\\|N\\|}$$`,
                  solution: `Let $F = (0, 2)$, $P = (0, 8)$, and $N = (0, 1)$. The conic section consisting of all points $X$ whose distance from $F$ is half the distance from $P$ is the set of $X$ satisfying the relation $$\\|X - F\\| = \\frac{1}{2}\\left|(X - P) \\cdot N\\right|$$Putting the vectors into $(x, y)$ coordinates $$\\|(x, y-2)\\| = \\frac{1}{2}\\left|(x, y - 8) \\cdot (0, 1)\\right|$$Squaring both sides $$x^{2} + (y - 2)^{2} = \\frac{1}{4}(y - 8)^{2}$$Expanding the expressions and rearranging terms into standard form we get $$\\frac{x^{2}}{12} + \\frac{y^{2}}{16} = 1\\quad \\blacksquare$$`,
                  date: "2024-12-04"
                },
                {
                  id: 8,
                  number: "13.25.8",
                  content: `Find a Cartesian equation for the parabola whose focus is at the origin and whose directrix is the line $x + y + 1 = 0$`,
                  hint: `Recall that a parabola is a conic section with eccentricity equal to 1. For more information, see the hint from (13.25.7)`,
                  solution: `The parabola whose focus is at the origin and whose directrix is the line $x + y + 1 = 0$ is the set of $X$ satisfying the relation $$\\|X\\| = \\frac{\\left|(X-P)\\cdot N\\right|}{\\|N\\|}$$where $P = (0, 1)$ and $N = (1, 1)$. Putting the vectors into $(x, y)$ coordinates and squaring both sides we get $$x^{2} + y^{2} = \\frac{1}{2}(x + y+ 1)^{2}$$Expanding the right side and rearranging terms gives us $$x^{2} - 2xy + y^{2} - 2x - 2y = 1 \\quad \\blacksquare$$`,
                  date: "2024-12-04"
                },
                {
                  id: 9,
                  number: "13.25.9",
                  content: `Find a Cartesian equation for a hyperbola passing through the origin, given that its asymptotes are the lines $y = 2x + 1$ and $y = -2x + 3$`,
                  hint: `Write the Cartesian equation for the hyperbola assuming its directrices are horizontal lines, ie. $$\\frac{y^{2}}{a^{2}} - \\frac{x^{2}}{b^{2}} = 1$$Rearranging variables, we see that $$y = \\pm \\frac{a}{\\left|b\\right|}\\sqrt{b^{2} + x^{2}}$$ For large positive $x$, the value $\\sqrt{b^{2} + x^{2}}$ is nearly equal to $x$, thus the value $y = \\pm \\frac{a}{\\left|b\\right|}\\sqrt{b^{2} + x^{2}}$ approaches $\\pm \\frac{ax}{\\left|b\\right|}$ asymptotically. We can use the asymptote equations to calculate the values of $a$ and $b$. Additionally, we can take the center of the center of the hyperbola as the point where its asymptotes intersect.`,
                  solution: `To find the center of the hyperbola, we find the point at which its asymptotes intersect. Setting $2x + 1 = -2x + 3$ we find $x = \\frac{1}{2}$ and $y = 2x + 1 = 2$. Thus, the standard form for our hyperbola becomes $$\\frac{(y - 2)^{2}}{a^{2}} - \\frac{(x - \\frac{1}{2})^{2}}{b^{2}} = 1$$where $b^{2} = a^{2}(e^{2} - 1)$. Since we know the hyperbola passes through the origin, we can substitute $x = 0$ and $y = 0$ giving us $$\\frac{4}{a^{2}} - \\frac{1}{4b^{2}} = 1$$Given the value $y = \\pm \\frac{a}{\\left|b\\right|} \\sqrt{b^{2} + x^{2}}$ approaches $\\pm \\frac{ax}{\\left|b\\right|}$ asymptotically, we see that $\\frac{a}{b}$ approaches $\\pm 2$, thus $b^{2}$ approaches $\\frac{a^{2}}{4}$, turning the above relation into $$\\frac{3}{a^{2}} = 1$$or in other words, $a^{2} = 3$ and $b^{2} = \\frac{a^{2}}{4} = \\frac{3}{4}$. Plugging this back into our standard equation, we get $$(y - 2)^{2} - 4(x - \\frac{1}{2})^{2} = 3$$Expanding and rearranging terms, we get $$y^{2} - 4x^{2} - 4y + 4x = 0 \\quad \\blacksquare$$`,
                  date: "2024-12-04"
                },
                {
                  id: 10,
                  number: "13.25.10",
                  content: `(a) For each $p>0$, the equation $px^{2} + (p+2)y^{2} = p^{2} + 2p$ represents an ellipse. Find (in terms of $p$) the eccentricity and the coordinates of the foci.\n(b) Find a Cartesian equation for the hyperbola which has the same foci as the ellipse of part (a) and which has eccentricity $\\sqrt{3}$.`,
                  hint: `(a) Rearrange the terms of the equation $px^{2} + (p+2)y^{2} = p^{2} + 2p$ to find the standard form of an ellipse. What are $a^{2}$ and $b^{2}$ in terms of $p$?\n(b) Recall the standard form of a hyperbola symmetric about the origin$$\\frac{x^{2}}{a^{2}} - \\frac{y^{2}}{b^{2}}$$where $b^{2} = a^{2}(e^{2} - 1)$. If the foci are the same as in part (a), but the eccentricity is $\\sqrt{3}$, what are $a^{2}$ and $b^{2}\\ $?`,
                  solution: `(a) Rearranging the terms of the equation $px^{2} + (p+2)y^{2} = p^{2} + 2p$, we get the standard form $$\\frac{x^{2}}{a^{2}} + \\frac{y^{2}}{b^{2}} = 1$$where $a^{2} = p+2$, $b^{2} = p$. Substituting $b^{2} = a^{2}(1 - e^{2})$ we find that $(1 - e^{2}) = \\frac{p}{p+2}$ or in other words, $$e = \\sqrt{\\frac{2}{p+2}}$$Since we know that the ellipse is symmetric about the origin with vertical directrices, we know that its foci are at the points $(ae, 0)$, $(-ae, 0)$, or $(\\sqrt{2}, 0)$ and $(-\\sqrt{2}, 0) \\quad \\blacksquare$\n\n(b) The foci of a hyperbola symmetric about the origin with vertical directrices are at the points $(ae, 0)$ and $(-ae, 0)$. From (a) we know that these points are $(\\sqrt{2}, 0)$ and $(-\\sqrt{2}, 0)$. But if $e = \\sqrt{3}$, then $\\pm ae = \\pm \\sqrt{3}a = \\pm \\sqrt{2}$, or in other words, $$a^{2} = \\frac{2}{3}$$giving us $$\\displaylines{b^{2} = a^{2}(e^{2} - 1)\\\\=\\frac{4}{3}}$$Substituting this into the Cartesian equation in standard form, we get $$\\frac{3x^{2}}{2} - \\frac{3y^{2}}{4} = 1$$or, $$6x^{2} - 3y^{2} = 4 \\quad \\blacksquare$$`,
                  date: "2024-12-06"
                },
                {
                  id: 11,
                  number: "13.25.11",
                  content: `In section 13.22 we proved that a conic symmetric about the origin satisfies the equation $\\|X - F\\| = \\left|eX \\cdot N - a\\right|$, where $a = ed + eF\\cdot N$. Use this relation to prove that $\\|X - F\\| + \\|X + F\\| = 2a$ if the conic is an ellipse. In other words, the sum of the distances from any point on an ellipse to its foci is constant.`,
                  hint: `From properties of the dot product (and by extension, the norm) we know that $\\|-X - F\\| = \\|X + F\\|$. Use this in conjunction with equation (13.29). $$\\|X - F\\| = e\\left|(X - F) \\cdot N - d\\right| = \\left|X \\cdot N - F \\cdot N - d\\right| = \\left|eX \\cdot N - a\\right|$$ Recall also that for a conic symmetric about the origin, $$a = \\frac{ed}{1 - e^{2}}; \\quad  F = \\frac{e^{2}d}{1 - e^{2}}N$$`,
                  solution: `We know that if a conic is symmetric about the origin, then for every $X$ on the curve, $-X$ must also be on the curve. Thus, if $X$ satisfies the equation $\\|X - F\\| = \\left|eX \\cdot N - a\\right|$, then $-X$ satisfies the equation $$\\|-X - F\\| = \\left|-eX \\cdot N - a\\right|$$But we know from the properties of the norm that $\\|-X - F\\| = \\|X + F\\|$, thus $$\\|X - F\\| + \\|X + F\\| = \\left|eX \\cdot N - a\\right| + \\left|-eX \\cdot N - a\\right|$$But since the conic is symmetric about the origin, we can set $a = \\frac{ed}{1 - e^{2}}$ turning the above equation into $$\\|X - F\\| + \\|X + F\\| = \\left|eX \\cdot N - \\frac{ed}{1 - e^{2}}\\right| + \\left|-eX \\cdot N - \\frac{ed}{1 - e^{2}}\\right|$$Since the equation $\\|X - F\\| = \\left|eX \\cdot N - a\\right|$ presumes that $X$ is in the negative half-plane, then we assume also that $X$ is to the right of the origin. That is, $eX \\cdot N > 0$. But this implies that $$\\left|eX \\cdot N - a\\right| = a - eX \\cdot N$$because the horizontal distance from the origin to X must be smaller than the horizontal distance from the origin to the right directrix. In other words, $eX \\cdot N < e\\frac{d}{1-e^{2}}$ (given that $e < 1$ and $N = \\textbf{i}$). And if we assume that $X$ is to the right of the origin, then $\\left|-eX \\cdot N - a\\right|$ becomes $eX \\cdot N + a$ since we know that $\\frac{ed}{1 - e^{2}} > 0$ because $d > 0$ and $e < 1$. Taking the sum of these terms, we see that $$\\displaylines{\\|X - F\\| + \\|X + F\\| = a - eX \\cdot N + eX \\cdot N + a\\\\=2a\\quad \\blacksquare}$$`,
                  date: "2024-12-06"
                },
                {
                  id: 12,
                  number: "13.25.12",
                  content: `Refer to Exercise 11. Prove that on each branch of a hyperbola the difference $\\|X - F\\|$ - $\\|X + F\\|$ is constant.`,
                  hint: `The setup is the same as in Exercise 11, but with the added change that for a hyperbola, the value $a = \\frac{ed}{1 - e^{2}}$ is less than zero since $e > 1$ for a hyperbola`,
                  solution: `Referring to the setup from Exercise 11, we know that $$\\|X - F\\| - \\|X + F\\| = \\left|eX \\cdot N - a\\right| - \\left|-eX \\cdot N - a\\right|$$If X is to the right of the origin, then $\\left|eX \\cdot N - a\\right| = eX \\cdot N - a$ since $a = \\frac{ed}{1 - e^{2}}$, which is less than zero for a hyperbola. And since $\\left|X \\cdot N\\right| < \\left|\\frac{d}{1 - e^{2}}\\right|$, $\\left|-eX \\cdot N - a\\right| = -eX \\cdot N - a$. Combining these two results, we get $$\\displaylines{\\|X - F\\| - \\|X + F\\| = eX \\cdot N - a - eX \\cdot N - a\\\\ =-2a \\quad \\blacksquare}$$`,
                  date: "2024-12-06"
                },
                {
                  id: 13,
                  number: "13.25.13",
                  content: `(a) Prove that a similarity transformation (replacing $x$ by $tx$ and $y$ by $ty$) carries an ellipse with center at the origin into another ellipse with the same eccentricity. In other words, similar ellipses have the same eccentricity.\n(b) Prove also the converse. That is, if two concentric ellipses have the same eccentricity and major axes on the same line, then they are related by similarity transform.\n(c) Prove results corresponding to (a) and (b) for hyperbolas.`,
                  hint: `Recall Theorem 13.19:\nLet $C$ be a conic section with eccentricity $e \\neq 1$ and with a focus $F$ at a distance $d$ from a directrix $L$. If $N$ is a unit normal to $L$ and if $F=eaN$, where $a = \\frac{ed}{1- e^{2}}$, then C is the set of all points $X$ satisfying the equation $$\\|X\\|^{2} + e^{2}a^{2} = e^{2}(X \\cdot N)^{2} + a^{2}$$This equation shows symmetry about the origin since the equation is satisfied by both $X$ and $-X$. Replacing $X$ by its rectangular coordinates $(x, y)$ and setting $N = \\textbf{i}$, we get: $$x^{2} + y^{2} + e^{2}a^{2} = e^{2}x^{2} + a^{2}$$What happens to this equation when $x$ is replaced by $tx$ and $y$ by $ty$? In other words, how do we maintain equality of both sides when $(x, y)$ is replaced by $(tx, ty)$?`,
                  solution: `(a) Recall that an ellipse symmetric about the origin is the set of $X$ satisfying the equation $$\\|X\\|^{2} + e^{2}a^{2} = e^{2}(X \\cdot N)^{2} + a^{2}$$where $e$ is the eccentricity, $a = \\frac{ed}{1 - e^{2}}$, and $d$ is the distance from the focus $F = eaN$ to a directrix $L$, and $N$ is the unit normal to $L$. Setting $X = (x, y)$ and $N = \\textbf{i}$, we get $$x^{2} + y^{2} + e^{2}a^{2} = e^{2}x^{2} + a^{2}$$This means that $e^{2} = 1 + \\frac{y^{2}}{x^{2} - a^{2}}$. Rearranging terms in the above equation, we get the following:$$x^{2} + y^{2} - e^{2}x^{2}  = a^{2} - e^{2}a^{2}$$Now, suppose that we transform $X$ by a scalar $t$, in other words, $(x, y)$ becomes $(tx, ty)$. The left-hand side of the above equation then becomes $t^{2}(x^{2} + y^{2} - e^{2}x^{2})$. But to maintain equality, we must also multiply the right-hand side by $t^{2}$. However, solving for $e^{2}$, we see that $$\\displaylines{e^{2} = \\frac{t^{2}(x^{2} - a^{2} + y^{2})}{t^{2}(x^{2} - a^{2})}\\\\= 1 + \\frac{y^{2}}{x^{2} - a^{2}}}$$Thus proving that transforming $X$ by a scalar $t$ leaves the eccentricity unchanged. This implies that scaling $X$ requires that $d$ be transformed by the same scalar.\n\n(b) Suppose for simplicity that the ellipses are concentric at the origin. Then, their major axes are the segments between $\\pm a_{0}N$ and $\\pm a_1{N}$ respectively, where $$a_{0} = \\frac{ed_{0}}{1 - e^{2}}; \\quad a_{1} = \\frac{ed_{1}}{1 - e^{2}}$$and where $d_{0}$ and $d_{1}$ are the distances between the foci of the respective ellipses and their corresponding directrices. Since $e$ is the same value in both $a_{0}$ and $a_{1}$ we see that $$\\frac{a_{0}(1 - e^{2})}{d_{0}} = \\frac{a_{1}(1 - e^{2})}{d_{1}}$$Which implies that $a_{1} = \\frac{a_{0}}{t}$ where $t = \\frac{d_{0}}{d_{1}}$. The standard form equation for the ellipse with major axis $\\pm a_{1}N$ is $$\\frac{x^{2}}{a_{1}^{2}} + \\frac{y^{2}}{a_{1}^{2}(1 - e^{2})} = 1$$ But this is equivalent to $$\\frac{t^{2}x^{2}}{a_{0}^{2}} + \\frac{t^{2}y^{2}}{a_{0}^{2}(1 - e^{2})} = 1$$which is a scalar transform of the ellipse with major axis $\\pm a_{0}N \\quad \\blacksquare$\n\n(c) The proofs of (a) and (b) are valid for conic sections with $e \\neq 0$.`,
                  date: "2024-12-06"
                },
                {
                  id: 14,
                  number: "13.25.14",
                  content: `Use the Cartesian equation which represents all conics of eccentricity $e$ and center at the origin to prove that these conics are integral curves of the differential equation $y' = (e^{2} - 1)x/y.$\nNote: Since this is a homogeneous differential equation (Section 8.25), the set of all such conics of eccentricity $e$ is invariant under a similarity transformation. (Compare with exercise 13.)`,
                  hint: `The Cartesian equation is $$\\frac{x^{2}}{a^{2}} + \\frac{y^{2}}{a^{2}(1 - e^{2})} = 1$$What is its derivative?`,
                  solution: `Taking the derivative of $\\frac{x^{2}}{a^{2}} + \\frac{y^{2}}{a^{2}(1 - e^{2})} = 1$ with respect to $x$ we get $$\\frac{2x}{a^{2}} + \\frac{2y(y')}{a^{2}(1 - e^{2})} = 0$$Solving for $y'$, we get $$y' = (e^{2} - 1)\\frac{x}{y}$$But this implies that the set of Cartesian equations for a conic of eccentricity $e$ and center at the origin is the set of indefinite integrals of this function. $\\blacksquare$`,
                  date: "2024-12-07"
                },
                {
                  id: 15,
                  number: "13.25.15",
                  content: `(a) Prove that the collection of all parabolas is invariant under a similarity transformation. That is, a similarity transformation carries a parabola into a parabola.\n
(b) Find all the parabolas similar to $y = x^2$.`,
                  hint: `(a) What happens to the focus and directrix line after the parabola undergoes a similarity transformation?`,
                  solution: `(a) Let $X = (x, y)$ be a point on the parabola with the standard form equation $$y^2 = 4cx$$Then, let $tX = (tx, ty)$ be the similarity transformation of $X$, where $t \\neq 0$. The above equation becomes $$y^2 = 4kx$$ where $k = \\frac{c}{t}$. But this describes a parabola with focus at $(k, 0)$ and directrix line $x = -k \\quad \\blacksquare$

(b) Since we know that all parabolas are invariant under similarity transform, then for any $C \\neq 0$,$$y = 4Cx^2$$ is similar to $y = x^2 \\quad \\blacksquare$`,
                  date: "2024-12-23"
                },
                {
                  id: 16,
                  number: "13.25.16",
                  content: `The line $x - y + 4 = 0$ is tangent to the parabola $y^2 = 16x$. Find the point of contact.`,
                  hint: "Find $(x, y)$ such that $x - y + 4= 0$ and $y^2 = 16x$",
                  solution: `$$\\displaylines{y = x + 4; \\quad y^2 = 16\\\\ \\rightarrow x^2 + 8x + 16 = 16x\\\\ \\rightarrow (x - 4)^2 = 0\\\\ \\rightarrow x = 4,\\quad y = 8 \\quad \\blacksquare}$$`,
                  date: "2024-12-23"
                },
                {
                  id: 17,
                  number: "13.25.17",
                  content: `(a) Given $a ≠ 0$. If the two parabolas $y^2 = 4p(x - a)$ and $x^2 = 4qy$ are tangent to each other, show that the $x$-coordinate of the point of contact is determined by $a$ alone.\n
(b) Find a condition on $a$, $p$, and $q$ which expresses the fact that the two parabolas are tangent to each other.`,
                  hint: ``,
                  solution: `(a) First, we express the parabola $y^2 = 4p(x - a)$ as a function of $x$: $$y = 2\\sqrt{p(x-a)}$$Then, we note that if the two parabolas are tangent, there exists some common point $(x_0, y_0)$ at which the derivatives of the two functions are equal. In other words, at $(x_0, y_0)$: $$\\frac{x_0}{2q} = \\sqrt{\\frac{p}{x_0 - a}}$$Squaring both sides and rearranging terms gives us $$x_0^2(x_0 - a) = 4pq^2$$But we know that $(x_0 - a) = \\frac{y_0^2}{4p}$ and that $y_0 = \\frac{x_0^2}{4q}$, which means that $$(x_0 - a) = \\frac{x_0^4}{64pq^2}$$And since $4pq^2 = x_0^2(x_0 - a)$, this simplifies to $$x_0^4 = 16x_0^2(x_0 - a)^2$$Solving for $x_0$ we find that $$x_0 = \\frac{4}{3}a$$Thus proving that the $x$-coordinate of the point of contact is determined only by $a \\quad \\blacksquare$

(b) From (a) we know that the $x$-coordinate of the point of contact is $x_0 = \\frac{4}{3}a$, plugging this into the equations for the parabolas we get $$y_0^2 = \\frac{4p}{3}a; \\quad x_0^2 = 4qy_0 = \\frac{16}{9}a^2$$And their respective derivatives at $(x_0, y_0)$ are $$\\sqrt{\\frac{p}{x_0 - a}}; \\quad \\frac{x_0}{2q}$$Setting $x_0 = \\frac{4}{3}a$ and setting the derivatives equal to eachother, we get $$2a^2 = 9pq$$But since $x_0^2 = \\frac{16}{9}a^2 = 4qy_0$, this means that $a^2 = \\frac{9}{4}qy_0$ and that $$2a^2 = 9pq = \\frac{9}{2}qy_0$$meaning that $y_0 = 2p$. And since $y_0^2 = \\frac{4p}{3}a$, this means that $a = 3p$ and $q = 2p$. 

Plugging these values back into our previous equation of derivatives, we find the following condition on $a$, $p$, and $q$ which expresses the fact that the two parabolas are tangent to eachother: $$4a^3 = 27pq^2 \\quad \\blacksquare$$`,
                  date: "2024-12-23"
                },
                {
                  id: 18,
                  number: "13.25.18",
                  content: `Consider the locus of the points $P$ in the plane for which the distance of $P$ from the point $(2, 3)$ is equal to the sum of the distances of $P$ from the two coordinate axes.\n
(a) Show that the part of this locus which lies in the first quadrant is part of a hyperbola. Locate the asymptotes and make a sketch.
(b) Sketch the graph of the locus in the other quadrants.`,
                  hint: "If we set the focus $F = (2, 3)$, then the distance $\\|P - F \\| = x + y$. This means for some eccentricity $e > 0$, $$x + y = ed(P, L)$$where $d(P, L)$ is the distance from $P$ to the directrix line $L$.",
                  solution: `(a) Let the focus $F = (2, 3)$, then the distance $\\|P - F \\| = x + y$. Then, for some directrix $L$ and eccentricity $e > 0$, $$x + y = ed(P, L)$$where $d(P, L)$ is the distance from $P$ to $L$. But by definition, if $N$ is the vector normal to $L$ and $X$ is a point on $L$, $d(P, L) = \\frac{|(P - X) \\cdot N|}{\\|N\\|}$. Applying this to our previous equation we see that $$\\frac{x + y}{e} = \\frac{|(P - X) \\cdot N|}{\\|N\\|}$$But since $P = (x, y)$ if we denote $X = (x_0, y_0)$, this means that $(P - X) \\cdot N = (x - x_0, y - y_0)\\cdot N = (x + y),$ which is satisfied by $X = O$ and $N = (1, 1)$. But if $N = (1, 1)$, then $\\|N\\| = \\sqrt{2}$, thus $e$ must also be $\\sqrt{2}$ if the above equation is to be satisfied. Thus, the locus of points $P$ in $Q1$ whose distance from $F = (2,3)$ is equal to $(x + y)$ must be part of a hyperbola since $e > 1$.

To find the asymptote lines of the hyperbola, recall that $\\|P - F\\| = x + y$, which means that if we square both sides we get $$2xy + 4x + 6y = 13$$Put in terms of $y$ we get $$y = \\frac{13 - 4x}{2x + 6}$$As $x$ approaches either $+\\infty$ or $-\\infty$, we see that the limit of $y$ goes to $-2$. As $x$ approaches $-3$ from the left, we see that $y$ goes to $-\\infty$ and likewise $y$ goes to $+\\infty$ as $x$ approaches $-3$ from the right. Thus, the asymptote lines of the hyperbola are the lines $x = -3$ and $y = -2$`,
                  date: "2024-12-23"
                },
                {
                  id: 19,
                  number: "13.25.19",
                  content: `Two parabolas have the same point as focus and the same line as axis, but their vertices lie on opposite sides of the focus. Prove that the parabolas intersect orthogonally (i.e., their tangent lines are perpendicular at the points of intersection).`,
                  hint: ``,
                  solution: `We know by definition that the vertex is the point midway between the directrix and the focus. Suppose the vertex of one parabola is at $O$ and its focus at $(c, 0)$, then this implies that the second vertex with the same focus is at $(2c, 0)$. If the standard form equation for the first parabola is $y^2 = 4cx$, then the second parabola, translated by $(2c, 0)$ and which opens in the opposite direction, has standard form equation $y^2 = -4c(x - 2c)$.

Taking these equations as functions of y, we get $$x = \\frac{y^2}{4c}; \\quad x = 2c - \\frac{y^2}{4c}$$Setting these equal to one-another, we find the points of intersection occur when $y^2 = 4c^2$. In other words, the graphs intersect at $(c, -2c)$ and $(c, 2c)$. Taking their respective derivatives gives us $$x' = \\frac{y}{2c}; \\quad x' = \\frac{-y}{2c}$$Evaluated at $(c, 2c)$ we get slopes $1$ and $-1$ respectively, which can be represented by the vectors $(1, 1)$ and $(1, -1)$, the dot product of which is $0$. Evaluating the derivatives at $(c, -2c)$ yield vectors $(1, -1)$ and $(1, 1)$, whose dot product is also $0$. Thus, we have proven that the two parabolas intersect orthogonally. $\\quad \\blacksquare$`,
                  date: "2024-12-23"
                },
                {
                  id: 20,
                  number: "13.25.20",
                  content: `(a) Prove that the Cartesian equation $$\\frac{x^2}{a^2} + \\frac{y^2}{a^2 - c^2} = 1$$represents all conics symmetric about the origin with foci at $(c, 0)$ and $(-c, 0)$.\n
(b) Keep $c$ fixed and let $S$ denote the set of all such conics obtained as $a^2$ varies over all positive numbers $> c^2$. Prove that every curve in $S$ satisfies the differential equation $$xy\\left(\\frac{dy}{dx}\\right)^2 + (x^2 - y^2 - c^2)\\frac{dy}{dx} - xy = 0.$$(c) Prove that $S$ is self-orthogonal; that is, the set of all orthogonal trajectories of curves in $S$ is $S$ itself. [Hint: Replace $y'$ by $-1/y'$ in the differential equation in (b).]`,
                  hint: `(a) Turn the Cartesian equation provided into a standard form equation. What is $e^2$ in this case? 

(b) The right-hand side of the derivative of the Cartesian equation in (a) is 0, this allows for multiplication of both sides by different values while maintaining equality.

(c) Perform the subsitution suggested by the hint in the problem and then multiply both sides by $-(y')^2$.`,
                  solution: `(a) If we set $e^2 = \\frac{c^2}{a^2}$, then the Cartesian equation becomes $$\\frac{x^2}{a^2} + \\frac{y^2}{a^2(1 - e^2)} = 1$$Simplifying terms, we get $$x^2(1 - e^2) + y^2 = a^2(1 - e^2)$$If we denote $X = (x, y)$ and let $N = \\textbf{i}$, then rearranging terms gives us $$\\|X\\|^2 + e^2a^2 = e^2(X \\cdot N)^2 + a^2$$But if $F = c = eaN$ where $a = \\frac{ed}{1 - e^2}$ with $d$ being the distance from $F$ to the directrix line $L$, then the set of points satisfying the Cartesian equation $$\\frac{x^2}{a^2} + \\frac{y^2}{a^2 - c^2} = 1$$is a conic section with eccentricity $e \\neq 1$, symmetric about the origin as per Theorem 13.19 $\\quad \\blacksquare$
                  
(b) First, we take the derivative with respect to $x$ of the Cartesian equation in (a): $$\\frac{2x}{a^2} + \\frac{2yy'}{a^2 - c^2} = 0$$This simplifies to $$a^2(x + yy') - c^2 = 0$$Which we can then rewrite as $$\\left(\\frac{a^2 - c^2}{a^2}\\right)x + yy' = 0$$This equation remains unchanged when multipliying both sides by $x$: $$\\left(\\frac{a^2 - c^2}{a^2}\\right)x^2 + xyy' = 0$$But from the Cartesian equation we know that $\\left(\\frac{a^2 - c^2}{a^2}\\right)x^2 = (a^2 - c^2 - y^2)$, giving us $$(a^2 - c^2 - y^2) + xyy' = 0$$Again we use the Cartesian equation to show that $a^2 = x^2 + \\frac{a^2y^2}{a^2 - c^2}$, giving us $$\\left(x^2 + \\frac{a^2y^2}{a^2 - c^2}\\right) - c^2 - y^2 + xyy' = 0$$Multiplying both sides by $y'$ and rearranging terms, we get $$xy(y')^2 +(x^2 - y^2 - c^2)y' + \\frac{a^2y^2y'}{a^2 - c^2} = 0$$But we know from the derivative of the Cartesian equation that $x = \\frac{-a^2yy'}{a^2-c^2}$, turning the above equation (substituting the Leibniz notation $\\frac{dy}{dx}$ for $y'$) into: $$xy\\left(\\frac{dy}{dx}\\right)^2 + (x^2 - y^2 - c^2)\\frac{dy}{dx}  - xy = 0 \\quad \\blacksquare$$
(c) If we replace $y'$ with $-\\frac{1}{y'}$ in the equation from part (b), we get $$\\frac{xy}{(y')^2} - \\frac{(x^2 - y^2 - c^2)}{y'} - xy = 0$$Multiplying both sides by $-(y')^2$, we get $$xy(y')^2 + (x^2 - y^2 - c^2)y' - xy = 0$$Thus showing that any curve in $S$ is self-orthogonal as the differential equation is satisfied equally by $y'$ and $-1/y' \\quad \\blacksquare$`,
                  date: "2024-12-23"
                },
                {
                  id: 21,
                  number: "13.25.21",
                  content: `Show that the locus of the centers of a family of circles, all of which pass through a given point and are tangent to a given line, is a parabola.`,
                  hint: "If you're trying to calculate it, you're doing it wrong.",
                  solution: "Let the given point be the focus $F$, and the tangent line be the directrix $L$. Then, since $F$ and the point of contact $P$ on $L$ are both on the circle, then they are both the same distance from the center of the circle. In other words, the locus of centers is the set of $X$ satisfying $$\\|X - F\\| = d(X, L)$$which is, by definition, a parabola. $\\quad \\blacksquare$",
                  date: "2024-12-23"
                },
                {
                  id: 22,
                  number: "13.25.22",
                  content: `Show that the locus of the centers of a family of circles, all of which are tangent (externally) to a given circle and also to a given straight line, is a parabola. (Exercise 21 can be considered to be a special case.)`,
                  hint: "This solution follows the same logic as that of (13.25.21)",
                  solution: "We know that a parabola is symmetric about its axis, thus the chord of length $8|c|$ can be broken down into two chords of length $4|c|$",
                  date: "2024-12-23"
                },
                {
                  id: 23,
                  number: "13.25.23",
                  content: `(a) A chord of length $8|c|$ is drawn perpendicular to the axis of the parabola $y^2 = 4cx$. Let $P$ and $Q$ be the points where the chord meets the parabola. Show that the vector from $O$ to $P$ is perpendicular to that from $O$ to $Q$.\n
(b) The chord of a parabola drawn through the focus and parallel to the directrix is called the latus rectum. Show first that the length of the latus rectum is twice the distance from the focus to the directrix, and then show that the tangents to the parabola at both ends of the latus rectum intersect the axis of the parabola on the directrix.`,
                  hint: `(a) Recall that a parabola is symmetric about its axis (that is, the line defined by the focus and vertex). What can we deduce from this symmetry regarding the chord from $P$ to $Q$?

(b) What are the points at which the latus rectum intersect with the parabola? What is the derivative of the function at those two points?`,
                  solution: `(a) The parabola described by the Cartesian equation $y^2 = 4cx$ is symmetric about the $x$-axis, thus the chord of length $8|c|$ drawn perpendicular to the $x$ axis can be described as two chords of length $4|c|$ drawn from the $x$-axis to the points $P = (4c, 4c)$ and $Q = (4c, -4c)$. Taking the dot product of these two points (that, is, vectors from $O$ to $P$ and $Q$, respectively), we get $0$. Thus, the two vectors are perpendicular. $\\blacksquare$

(b) First, we note that the Cartesian equation $y^2 = 4cx$ describes a parabola with focus $F = (c, 0)$ and vertex at $O$, thus putting the directrix line at $x = -c$, making the axis of the parabola the $x$ axis. 

Then, we find the points on the parabola where $x = c$, giving us $(c, 2c)$ and $(c, -2c)$. This means that the length of the latus rectum is $4c$. But we know that the distance from $(c, 0)$ to $(-c, 0)$ is $2c$, thus the latus rectum has length of twice the distance from the focus to the directrix. To find the slope of the lines tangent to the parabola at $(c, 2c)$ and $(c, -2c)$, we take the derivative with respect to $y$: $$\\frac{d}{dy}\\left(\\frac{y^2}{4c}\\right) = \\frac{y}{2c}$$Evaluating this at $y=2c$ and $y=-2c$, we get slopes $1$ and $-1$, respectively, meaning that the line tangent to the parabola at $(c, 2c)$ has equation $x = y + b$. Evaluating the line at $(c, 2c),$ we find that $b$, the $x$-intercept, is $-c$, meaning that the line intercepts the $x$ axis through the directrix line. Doing this at $(c, -2c)$ gives a tangent line with equation $x = b - y$, evaluating at $(c, -2c)$ gives $b = -c$, meaning that this tangent line also intercepts the $x$ axis through the directrix line. This completes the proof.`,
                  date: "2024-12-23"
                },
                {
                  id: 24,
                  number: "13.25.24",
                  content: `Two points $P$ and $Q$ are said to be symmetric with respect to a circle if $P$ and $Q$ are collinear with the center, if the center is not between them, and if the product of their distances from the center is equal to the square of the radius. Given that $Q$ describes the straight line $x + 2y - 5 = 0$, find the locus of the point $P$ symmetric to $Q$ with respect to the circle $x^2 + y^2 = 4$.`,
                  hint: `From the given Cartesian equation, we know that the center of the circle is at the origin. If $P$ and $Q$ are collinear with $O$, with $O$ not being between between $P$ and $Q$, what is the relationship between $P$ and $Q$?`,
                  solution: `If points $P$ and $Q$ are collinear with the origin, but the origin is not between $P$ and $Q$, then this implies that $P$ is a positive scalar multiple of $Q$. In other words, $P = (u, v) = k(x, 2y)$, where $k > 0$. To find $k$, we note that the product of the lengths of $P$ and $Q$ must equal $4$, thus $$\\left(\\sqrt{x^2 + 4y^2}\\right)\\left(k\\sqrt{x^2 + ky^2}\\right) = 4$$In other words, $k\\left(x^2 + y^2\\right) = 4$, making $k = \\frac{4}{x^2 + 4y^2}$. Thus, the locus of $P$ is the set of points satisfying $k(x, 2y)$ where $x + 2y - 5 = 0$`,
                  date: "2024-12-23"
                }
              ]
            }
          ]
        },
        {
          id: 14,
          title: "Chapter 14: Calculus of Vector-Valued Functions",
          description: "This chapter combines vector algebra with the methods of calculus and describes some applications to the study of curves and to some problems in mechanics.",
          problemSets: [
            {
              id: 4,
              title: "14.4 Exercises",
              description: "Exercises on limits, derivatives, and integrals of vector-valued functions",
              problems: [
                {
                  id: 1,
                  number: "14.4.1",
                  content: `Compute the derivatives $F'(t)$ and $F''(t)$ for: $F(t) = (t, t^2, t^3, t^4)$`,
                  hint: ``,
                  solution: `Using the power rule of derivatives: $$\\displaylines{F'(t) &= (1, 2t, 3t^2, 4t^3)\\\\F''(t) &= (0, 2, 6t, 12t^2)}$$Note: the back-of-book solution has a typo which says $$F'(t) = (1, 2t, 3t^2 + 4t^3)$$`,
                  date: "2024-01-02"
                },
                {
                  id: 2,
                  number: "14.4.2",
                  content: `Compute the derivatives $F'(t)$ and $F''(t)$ for: $F(t) = (\\cos t, \\sin^2 t, \\sin 2t, \\tan t)$`,
                  hint: `Recall from section 2.5 that: $2\\ \\text{sin}(t)\\text{cos}(t) = \\text{sin}(2t)$.`,
                  solution: `$$\\displaylines{F'(t) &= (-\\text{sin}(t), 2\\ \\text{sin}(t)\\text{cos}(t), 2\\ \\text{cos}(2t), \\text{sec}^2(t)) \\\\ &= (-\\text{sin}(t), \\text{sin}(2t), 2\\ \\text{cos}(2t), \\text{sec}^2(t))}$$ $$\\displaylines{F''(t) &= (-\\text{cos}(t), 2\\text{cos}(2t), -4\\text{sin}(2t), 2\\text{sec}^2(t)\\text{tan}(t))}$$`,
                  date: "2024-01-02"
                },
                {
                  id: 3,
                  number: "14.4.3",
                  content: `Compute the derivatives $F'(t)$ and $F''(t)$ for: $F(t) = (\\arcsin t, \\arccos t)$`,
                  hint: `Recall from section 6.20 that: $$D(\\text{arcsin}(t)) = \\frac{1}{\\sqrt{1 - t^2}}$$if $-1 < t < 1$, and $$D(\\text{arccos}(t)) = \\frac{-1}{\\sqrt{1 - t^2}}$$if $-1 < t < 1$`,
                  solution: `$$F'(t) = \\left(\\frac{1}{\\sqrt{1 - t^2}}, \\frac{-1}{\\sqrt{1 - t^2}}\\right)$$ $$F''(t) = \\left(\\frac{t}{(1 - t^2)^{3/2}}, \\frac{-t}{(1 - t^2)^{3/2}}\\right)$$Note: the back-of-book solution has a typo which says that $$F''(t) = \\left(\\frac{t}{(1 + t^2)^{3/2}}, \\frac{-t}{(1 + t^2)^{3/2}}\\right)$$`,
                  date: "2024-01-02"
                },
                {
                  id: 4,
                  number: "14.4.4",
                  content: `Compute the derivatives $F'(t)$ and $F''(t)$ for: $F(t) = 2e^t \\mathbf{i} + 3e^t \\mathbf{j}$`,
                  hint: ``,
                  solution: `Since we know that $D(e^t) = e^t$, we have: $$F'(t) = F''(t) = F(t) = 2e^t \\mathbf{i} + 3e^t \\mathbf{j}$$`,
                  date: "2024-01-02"
                },
                {
                  id: 5,
                  number: "14.4.5",
                  content: `Compute the derivatives $F'(t)$ and $F''(t)$ for: $F(t) = \\cosh t\\mathbf{i} + \\sinh 2t\\mathbf{j} + e^{-3t}\\,\\mathbf{k}$`,
                  hint: `Recall from section 6.18 that $$\\text{sinh}(t) = \\frac{e^t - e^{-t}}{2};\\quad \\text{cosh}(t) = \\frac{e^t + e^{-t}}{2}$$This means that $$F(t) = \\left(\\frac{e^t + e^{-t}}{2}, \\frac{e^{2t} - e^{-2t}}{2}, e^{-3t}\\right)$$`,
                  solution: `$$F(t) = \\left(\\frac{e^t + e^{-t}}{2}, \\frac{e^{2t} - e^{-2t}}{2}, e^{-3t}\\right)$$$$\\displaylines{F'(t) &= \\left(\\frac{e^t - e^{-t}}{2}, e^{2t} + e^{-2t}, -3e^{-3t}\\right)\\\\ &=\\left(\\text{sinh}(t), 2\\text{cosh}(t), -3e^{-3t}\\right)}$$$$\\displaylines{F''(t) &= \\left(\\frac{e^t + e^{-t}}{2}, 2e^{2t} - 2e^{-2t}, 9e^{-3t}\\right)\\\\ &= \\left(\\text{cosh}(t), 4\\text{sinh}(2t), 9e^{-3t}\\right)}$$`,
                  date: "2024-01-02"
                },
                {
                  id: 6,
                  number: "14.4.6",
                  content: `Compute the derivatives $F'(t)$ and $F''(t)$ for: $F(t) = \\log(1 + t^2)\\mathbf{i} + \\arctan t\\mathbf{j} + \\frac{1}{1+t^2}\\,\\mathbf{k}$`,
                  hint: `Recall from section 6.20 that $$D(\\text{arctan}(t)) = \\frac{1}{1 + t^2}$$for all real $t$`,
                  solution: `$$F'(t) = \\left(\\frac{2t}{1 + t^2}, \\frac{1}{1 + t^2}, \\frac{-2t}{(1 + t^2)^2}\\right)$$$$F''(t) = \\left(\\frac{(2 - 2t^2)}{(1 + t^2)^2}, \\frac{-2t}{(1 + t^2)^2}, \\frac{6t^2 - 2}{(1 + t^2)^3}\\right)$$`,
                  date: "2024-01-02"
                },
                {
                  id: 7,
                  number: "14.4.7",
                  content: `Let $F$ be the vector-valued function given by: $$F(t) = \\frac{2t}{1+t^2}\\mathbf{i} + \\frac{1-t^2}{1+t^2}\\mathbf{j} + \\mathbf{k}$$Prove that the angle between $F(t)$ and $F'(t)$ is constant, that is, independent of $t$.`,
                  hint: `Recall from section 12.9 that the cosine of the angle between two vectors can be expressed in terms of their dot product and their norms: $$\\text{cos}\\ \\theta = \\frac{A \\cdot B}{\\|A\\|\\|B\\|}$$Then, if the cosine of the angle between the two vectors is constant, this imples that the angle itself is constant.`,
                  solution: `First, we calculate $F'(t)$:$$F'(t) = \\left(\\frac{2 - 2t^2}{(1 + t^2)^2}, \\frac{-4t}{(1 + t^2)^2}, 0\\right)$$Then, we calculate the dot product $F(t) \\cdot F'(t)$:$$F(t) \\cdot F'(t) = \\frac{4t(1 - t^2)}{(1 + t^2)^3} - \\frac{4t(1 - t^2)}{(1 + t^2)^3} = 0$$But this means that the cosine of the angle between $F(t)$ and $F'(t)$ is constant. Thus, the angle between the two vectors must be constant, that is, independent of $t. \\ \\blacksquare$ `,
                  date: "2024-01-02"
                },
                {
                  id: 8,
                  number: "14.4.8",
                  content: `Compute the vector-valued integral:$$\\int_0^1 (t, \\sqrt{t}, e^t)\\,dt$$`,
                  hint: ``,
                  solution: `Evaluating the integrals component-wise, we get: $$\\left(\\frac{t^2}{2},\\  \\frac{2}{3}t^{3/2},\\ e^t\\right)\\Biggr|_0^1 = \\left(\\frac{1}{2},\\ \\frac{3}{2},\\ e - 1\\right)$$`,
                  date: "2024-01-02"
                },
                {
                  id: 9,
                  number: "14.4.9",
                  content: `Compute the vector-valued integral:$$\\int_0^{\\pi/4} (\\sin t, \\cos t, \\tan t)\\,dt$$`,
                  hint: ``,
                  solution: `Evaluating the integrals component-wise, we get:$$\\displaylines{\\left(-\\text{cos}\\,t,\\  \\text{sin}\\,t,-\\text{log}\\,\\text{cos}\\,t\\right)\\,\\Biggr|_0^{\\pi/4} &= \\left(1 - \\frac{\\sqrt{2}}{2},\\ \\frac{\\sqrt{2}}{2},\\  -\\text{log}\\,\\frac{\\sqrt{2}}{2}\\right)\\\\ &= \\left(1 - \\frac{\\sqrt{2}}{2},\\ \\frac{\\sqrt{2}}{2},\\ \\frac{\\text{log}\\,{2}}{2}\\right)}$$Note: the back-of-book solution contains a typo for the rightmost element, which says $\\text{log}\\,\\frac{\\sqrt{2}}{2}$ instead of $-\\text{log}\\,\\frac{\\sqrt{2}}{2}$ or $\\frac{\\text{log}\\,{2}}{2}$.`,
                  date: "2024-01-02"
                },
                {
                  id: 10,
                  number: "14.4.10",
                  content: `Compute the vector-valued integral:$$\\int_0^1 \\left(\\frac{e^t}{1+e^t}\\mathbf{i} + \\frac{1}{1+e^t}\\mathbf{j}\\right)\\,dt$$`,
                  hint: `Use a $u$ substitution where $u(t) = 1 + e^t$ and $du = e^t\\, dt$. Then, rewrite $\\frac{1}{1 + e^t} = 1 - \\frac{e^t}{1 + e^t}$`,
                  solution: `Evaluating the integral, we get:$$\\displaylines{\\int_0^1 \\left(\\frac{e^t}{1+e^t}\\mathbf{i} + \\frac{1}{1+e^t}\\mathbf{j}\\right)\\,dt &= \\text{log}\\,(1 + e^t)\\mathbf{i} + t - \\log(1 + e^t)\\,\\mathbf{j}\\,\\Biggr|_0^1\\\\ &= \\text{log}\\frac{1 + e}{2}\\mathbf{i} + \\left(1 - \\text{log}\\frac{1 + e}{2}\\right)\\mathbf{j}}$$`,
                  date: "2024-01-02"
                },
                {
                  id: 11,
                  number: "14.4.11",
                  content: `Compute the vector-valued integral:$$\\int_0^1 (te^t\\mathbf{i} + t^2e^t\\mathbf{j} + te^{-t}\\,\\mathbf{k})\\,dt$$`,
                  hint: `Use integration by parts with $u = t^n$ and $dv = e^t\\, dt$`,
                  solution: `Using integration by parts on each component, we get:$$\\left(te^t - e^t\\right)\\Biggr|_0^1\\textbf{i}\\ + \\left(t^2e^t - 2(te^t - e^t)\\right)\\Biggr|_0^1\\textbf{j}\\ + \\left(-te^{-t} - e^{-t}\\right)\\Biggr|_0^1\\textbf{k}$$Evaluating over the limits of integration, we get:$$\\left(1,\\ e-2,\\ 1 - \\frac{2}{e}\\right)$$`,
                  date: "2024-01-02"
                },
                {
                  id: 12,
                  number: "14.4.12",
                  content: `Compute $A \\cdot B$, where $A = 2\\,\\mathbf{i} - 4\\,\\mathbf{j} + \\mathbf{k}$ and $B = \\int_0^2 (te^{2t}\\,\\mathbf{i} + t\\cosh 2t\\,\\mathbf{j} + 2te^{-t}\\,\\mathbf{k})\\,dt$`,
                  hint: `Recall from section 6.18 that $$\\text{sinh}\\,t = \\frac{e^t - e^{-t}}{2};\\quad \\text{cosh}\\,t = \\frac{e^t + e^{-t}}{2}$$`,
                  solution: `Note that $\\text{cosh}\\,2t = \\frac{e^{2t} + e^{-2t}}{2}$, then:$$B = \\int_0^2 (te^{2t}\\,\\mathbf{i} + \\frac{te^{2t} + te^{-2t}}{2}\\,\\mathbf{j} + 2te^{-2t}\\,\\mathbf{k})\\,dt$$Taking the dot product $A \\cdot B$, we get: $$A \\cdot B = \\int_0^2 2te^{2t} - 2te^{2t} - 2te^{-2t} + 2te^{-2t}\\, dt$$But the terms of the integrand simplify to $0$, thus $A \\cdot B = 0$.`,
                  date: "2024-01-02"
                },
                {
                  id: 13,
                  number: "14.4.13",
                  content: `Given a nonzero vector $B$ and a vector-valued function $F$ such that $F(t) \\cdot B = t$ for all $t$, and such that the angle between $F'(t)$ and $B$ is constant (independent of $t$). Prove that $F''(t)$ is orthogonal to $F'(t)$.`,
                  hint: `Recall the dot product identity from Theorem 14.1:$$\\left(F \\cdot G \\right)' = F' \\cdot G + F \\cdot G'$$If the angle between $F'$ and $B$ is constant, then the cosine of this angle is also constant. What does this imply about $F' \\cdot B$?`,
                  solution: `We know from the dot product identity in Theorem 14.1 that $$\\left(F \\cdot B \\right)' = F' \\cdot B + F \\cdot B'$$But $B$ is a vector of constants, so $B' = O$, and $F \\cdot B = t$, so $(F \\cdot B)' = 1$. Combining this with the above, we get $$\\left(F \\cdot B\\right)' = F' \\cdot B = 1$$Taking the derivative of $(F' \\cdot B)$, we see that $$F'' \\cdot B = 0$$But by definition, $B$ is nonzero, thus $F''(t)$ must be the zero vector, meaning that $F'' \\cdot F = 0$ for any $t$. Put another way, $F''(t)$ is orthogonal to $F'(t)$ for all $t. \\quad \\blacksquare$ `,
                  date: "2024-01-02"
                },
                {
                  id: 14,
                  number: "14.4.14",
                  content: `Given fixed nonzero vectors $A$ and $B$, let $F(t) = e^{2t}A + e^{-2t}B$. Prove that $F''(t)$ has the same direction as $F(t)$.`,
                  hint: `For two vectors $A$ and $B$ to have the same direction, then for some positive scalar $c$, $A$ = $cB$`,
                  solution: `It will suffice to show that for some positive scalar $c$, that $F''(t) = cF(t)$. Taking the second derivative of of $F(t)$: $$\\displaylines{F'(t) &= 2e^{2t}A - 2e^{-2t}B}$$$$\\displaylines{F''(t) &= 4e^{2t}A + 4e^{-2t}B\\\\ &= 4F(t) \\quad \\blacksquare}$$`,
                  date: "2024-01-02"
                },
                {
                  id: 15,
                  number: "14.4.15",
                  content: `If $G = F \\times F'$, compute $G'$ in terms of $F$ and derivatives of $F$.`,
                  hint: `Use the cross product identity from Theorem 14.1:$$(F \\times G)' = F' \\times G + F \\times G'$$and recall from section 13.9 that $A \\times B = O$ if and only if $A$ and $B$ are linearly dependent.`,
                  solution: `Using the cross product identity from theorem 14.1: $$(F \\times F')' = F' \\times F' + F \\times F''$$And since F' is linearly dependent to itself, $F' \\times F' = O$, giving us $$G' = F \\times F''$$`,
                  date: "2024-01-02"
                },
                {
                  id: 16,
                  number: "14.4.16",
                  content: `If $G = F \\cdot F' \\times F''$, prove that $G' = F \\cdot F' \\times F'''$.`,
                  hint: `Recall from section 13.9 that the cross product of two vectors is orthogonal to those two vectors.`,
                  solution: `Taking the dot product first, we get: $$F \\cdot \\left(F' \\times F''\\right) = F' \\cdot \\left(F ' \\times F''\\right) + F \\cdot \\left(F ' \\times F''\\right)'$$But since the cross product of two vectors is orthogonal to those two vectors, $F' \\cdot \\left(F' \\times F''\\right) = O$\n\nUsing this and extending the result of problem (15) to $\\left(F' \\times F''\\right)'$, we see that $$G' = F \\cdot \\left(F' \\times F'''\\right) \\quad \\blacksquare$$`,
                  date: "2024-01-02"
                },
                {
                  id: 17,
                  number: "14.4.17",
                  content: `Prove that $\\lim_{t\\to p} F(t) = A$ if and only if $\\lim_{t\\to p} \\|F(t) - A\\| = 0$.`,
                  hint: `If $\\lim_{t \\to\\ p}\\|F(t) - A\\| = 0$, then it must be the case that $\\lim_{t \\to\\ p}\\|F(t) - A\\|^2 = 0$`,
                  solution: `If $\\lim_{t \\to\\ p}F(t) = A$, then it follows that $\\lim_{t \\to\\ p}\\|F(t) - A\\| = 0$. Now, suppose that $\\lim_{t \\to\\ p}\\|F(t) - A\\| = 0$, this means that $\\lim_{t \\to\\ p}\\|F(t) - A\\|^2 = 0$, or in other words: $$\\lim_{t \\to\\ p}\\left[F(t) - A\\right] \\cdot \\left[F(t) - A\\right] = 0$$But this implies that $C = \\left[F(t) - A\\right] \\to 0$ as $t \\to p$. In other words, $$\\lim_{t \\to \\ p} F(t) = A$$Thus, we have shown that $\\lim_{t\\to p} F(t) = A$ if and only if $\\lim_{t\\to p} \\|F(t) - A\\| = 0. \\quad \\blacksquare$`,
                  date: "2024-01-02"
                },
                {
                  id: 18,
                  number: "14.4.18",
                  content: `Prove that a vector-valued function $F$ is differentiable on an open interval $I$ if and only if for each $t$ in $I$ we have:$$F'(t) = \\lim_{h\\to 0} \\frac{1}{h}[F(t + h) - F(t)]$$`,
                  hint: ``,
                  solution: `By definition, a vector-valued function is differentiable on an open interval $I$ if and only if every component is differentiable on that open interval. In other words, for each component $f$ of $F$, $$f'(t) = \\lim_{h \\to 0}\\frac{1}{h}\\left[f(t + h) - f(t)\\right]$$for all $t$ in the open interval $I$.`,
                  date: "2024-01-02"
                },
                {
                  id: 19,
                  number: "14.4.19",
                  content: `Prove the zero-derivative theorem for vector-valued functions. If $F'(t) = O$ for each $t$ in an open interval $I$, then there is a vector $C$ such that $F(t) = C$ for all $t$ in $I$.`,
                  hint: ``,
                  solution: `In problem (18), we showed that a vector-valued function is differentiable if and only if for every $t$ in an open interval $I$, and for every component $f_i$ of $F$, $$f_i'(t) = \\lim_{h \\to 0}\\frac{1}{h}\\left[f_i(t + h) - f_i(t)\\right]$$Now, suppose that for every $t$ in the open interval $I$, $f_i'(t) = 0$. Then, the above limit can be rewritten as $$\\lim_{h \\to 0}\\frac{1}{h}\\,f_i(t + h) = f_i(t)$$But this implies that there is some real scalar $c_i$ such that for every $t$ in $I$, $f_i(t) = c_i$. But if this is true for each $f_i$ of $F$, then the vector-valued function $F(t) = C$ on the open interval $I$, where $C = (c_1, ..., c_n)$`,
                  date: "2024-01-02"
                },
                {
                  id: 20,
                  number: "14.4.20",
                  content: `Given fixed vectors $A$ and $B$ and a vector-valued function $F$ such that $F''(t) = tA + B$, determine $F(t)$ if $F(0) = D$ and $F'(0) = C$.`,
                  hint: ``,
                  solution: `Using the definition of an integral for a vector-valued function along with the second fundamental theorem, we have: $$\\displaylines{F'(t) = \\int_0^tF''(t)\\,dt + F'(0)\\\\ =\\frac{t^{2}}{2}A + Bt + C}$$Integrating and applying the second fundamental theorem again: $$\\displaylines{F(t) = \\int_0^t F'(t)\\, dt + F(0)\\\\ = \\frac{t^3}{6}A + \\frac{t^2}{2}B + Ct + D}$$`,
                  date: "2024-01-02"
                },
                {
                  id: 21,
                  number: "14.4.21",
                  content: `A differential equation of the form $Y'(x) + p(x)Y(x) = Q(x)$, where $p$ is a given real-valued function, $Q$ a given vector-valued function, and $Y$ an unknown vector-valued function, is called a first-order linear vector differential equation. Prove that if $p$ and $Q$ are continuous on an interval $I$, then for each $a$ in $I$ and each vector $B$ there is one and only one solution $Y$ which satisfies the initial condition $Y(a) = B$, and that this solution is given by the formula:\n$Y(t) = Be^{-q(t)} + e^{-q(t)}\\int_a^t Q(x)e^{q(x)}\\,dx$\nwhere $q(x) = \\int_a^x p(t)\\,dt$.`,
                  hint: ``,
                  solution: `We can apply the result of Theorem 8.3 component-wise to achieve this result for a vector-valued function.`,
                  date: "2024-01-02"
                },
                {
                  id: 22,
                  number: "14.4.22",
                  content: `A vector-valued function $F$ satisfies the equation $tF'(t) = F(t) + tA$ for each $t \\geq 0$, where $A$ is a fixed vector. Compute $F''(1)$ and $F(3)$ in terms of $A$, if $F(1) = 2A$.`,
                  hint: `To apply the second fundamental theorem, use the given value for $F(1)$ and calculate $F'(1)$ using the given equation.`,
                  solution: `Taking the derivative of the given equation, we get $$tF''(t) = A$$Thus, $F''(1) = A$. Now, to find $F(3)$, consider that by rearranging the given equation, we can express $F(t)$ as $$F(t) = tF'(t) - tA$$But since $F(1) = 2A$, this means that $F'(1) = F(1) + A = 3A$.\n\nRewriting $F''(t) = \\frac{A}{t}$ for $t > 0$ with $F'(1) = 3A$ we can integrate $F''(t)$ giving us: $$F'(t) - F'(1) = \\int_1^t \\frac{A}{x}\\,dx$$Evaluating the integral gives us $$F'(t) = A\\text{log}\\,t + 3A$$Integrating again with $F(1) = 2A$, we find that $$F(t) = \\int_1^t A\\text{log}\\,x + 3A\\,dx + 2A$$Evaluating the integral for $t = 3$, we get $$\\displaylines{F(3) &= Ax\\text{log}\\,x + 2Ax\\,\\Biggr|_1^3 + 2A\\\\&= (6 + 3\\text{log}\\,3)A \\quad \\blacksquare}$$`,
                  date: "2024-01-02"
                },
                {
                  id: 23,
                  number: "14.4.23",
                  content: `Find a vector-valued function $F$, continuous on the interval $(0, +\\infty)$, such that:$$F(x) = xe^xA + \\frac{1}{x}\\int_1^x F(t)\\,dt$$for all $x > 0$, where $A$ is a fixed nonzero vector.`,
                  hint: `Multiply both sides by $x$ before differentiating.`,
                  solution: `Multiplying both sides by $x$, we get$$xF(x) = x^2e^xA + \\int_1^x F(t)\\,dt$$Taking the derivative with respect to $x$, we get $$F(x) + xF'(x) = 2xe^xA + F(x)$$Simplifying terms gives us $F'(x) = 2e^xA + xe^xA.$Integrating both sides using the second fundamental theorem with $F(1) = eA$, we get$$\\displaylines{F(x) &= eA + \\int_1^x 2e^tA + te^tA\\,dt\\\\ &= 2e^tA\\,\\Biggr|_1^x + \\int_1^x te^tA\\,dt + eA\\\\&= e^tA + te^tA\\,\\Biggr|_1^x + eA \\\\&= e^x(x + 1)A - eA \\quad \\blacksquare}$$`,
                  date: "2024-01-02"
                },
                {
                  id: 24,
                  number: "14.4.24",
                  content: `A vector-valued function $F$, which is never zero and has a continuous derivative $F'(t)$ for all $t$, is always parallel to its derivative. Prove that there is a constant vector $A$ and a positive real-valued function $u$ such that $F(t) = u(t)A$ for all $t$.`,
                  hint: `By definition, two vectors $A$ and $B$ are parallel if for some nonzero scalar $c$, $B = cA$.`,
                  solution: `If we set $u(t) = e^{ct}$ for some nonzero $c$, then it follows that $u$ is positive for all $t$, $F(t)$ is never zero, and $F'(t)$ is parallel to $F(t)$ for all $t$.`,
                  date: "2024-01-02"
                }
              ]
            },
            {
              id: 7,
              title: "14.7 Exercises",
              description: "Exercises on the calculus of vector-valued functions with applications to curve tangency and curvilinear motion.",
              problems: [
                {
                  id: 1,
                  number: "14.7.1",
                  content: `In each of Exercises 1 through 6, $\\textbf{r}(t)$ denotes the position vector at time $t$ for a particle moving on a space curve. Determine the velocity $\\textbf{v}(t)$ and acceleration $\\textbf{a}(t)$ in terms of $\\mathbf{i}, \\mathbf{j}, \\mathbf{k}$; also, compute the speed $v(t)$.\n\n$$\\textbf{r}(t) = (3t - t^3)\\,\\mathbf{i} + 3t^3\\,\\mathbf{j} + (3t + t^3)\\,\\mathbf{k}$$`,
                  hint: ``,
                  solution: `$$\\displaylines{\\textbf{v}(t) = (3 - 3t^2)\\,\\textbf{i} + 6t\\,\\textbf{j} + (3 + 3t^2)\\textbf{k}\\\\ \\textbf{a}(t) = -6t\\,\\textbf{i} + 6\\,\\textbf{j} + 6t\\,\\textbf{k}\\\\ v(t) = 3\\sqrt{2}(1 + t^2)}$$`,
                  date: "2024-01-27"
                },
                {
                  id: 2,
                  number: "14.7.2",
                  content: `In each of Exercises 1 through 6, $\\textbf{r}(t)$ denotes the position vector at time $t$ for a particle moving on a space curve. Determine the velocity $\\textbf{v}(t)$ and acceleration $\\textbf{a}(t)$ in terms of $\\mathbf{i}, \\mathbf{j}, \\mathbf{k}$; also, compute the speed $v(t)$.\n\n$$\\textbf{r}(t) = \\cos t\\,\\mathbf{i} + \\sin t\\,\\mathbf{j} + e^t\\,\\mathbf{k}$$`,
                  hint: ``,
                  solution: `$$\\displaylines{\\textbf{v}(t) = -\\text{sin}\\,t\\,\\textbf{i} + \\text{cos}\\,t\\,\\textbf{j} + e^t\\,\\textbf{k}\\\\ \\textbf{a}(t) = -\\text{cos}\\,t\\,\\textbf{i} - \\text{sin}\\,t\\,\\textbf{j} + e^t\\,\\textbf{k} \\\\ v(t) = \\left(1 + e^{2t}\\right)^{1/2}}$$`,
                  date: "2024-01-27"
                },
                {
                  id: 3,
                  number: "14.7.3",
                  content: `In each of Exercises 1 through 6, $\\textbf{r}(t)$ denotes the position vector at time $t$ for a particle moving on a space curve. Determine the velocity $\\textbf{v}(t)$ and acceleration $\\textbf{a}(t)$ in terms of $\\mathbf{i}, \\mathbf{j}, \\mathbf{k}$; also, compute the speed $v(t)$.\n\n$$\\textbf{r}(t) = 3t\\cos t\\mathbf{i} + 3t\\sin t\\mathbf{j} + 4t\\,\\mathbf{k}$$`,
                  hint: ``,
                  solution: `$$\\displaylines{\\mathbf{v}(t) = (3\\,\\text{cos}\\,t - 3t\\,\\text{sin}\\,t)\\, \\mathbf{i} + (3\\,\\text{sin}\\,t + 3t\\,\\text{cos}\\,t)\\,\\mathbf{j} + 4\\,\\textbf{k}\\\\ \\mathbf{a}(t) = (-6\\,\\text{sin}\\,t - 3t\\,\\text{cos}\\,t)\\,\\mathbf{i} + (6\\,\\text{cos}\\,t - 3t\\,\\text{sin}\\,t)\\,\\mathbf{j}\\\\ v(t) = \\sqrt{9t^2 + 25}}$$`,
                  date: "2024-01-27"
                },
                {
                  id: 4,
                  number: "14.7.4",
                  content: `In each of Exercises 1 through 6, $\\textbf{r}(t)$ denotes the position vector at time $t$ for a particle moving on a space curve. Determine the velocity $\\textbf{v}(t)$ and acceleration $\\textbf{a}(t)$ in terms of $\\mathbf{i}, \\mathbf{j}, \\mathbf{k}$; also, compute the speed $v(t)$.\n$$\\textbf{r}(t) = (t - \\sin t)\\mathbf{i} + (1 - \\cos t)\\mathbf{j} + 4\\sin \\frac{t}{2}\\mathbf{k}$$`,
                  hint: ``,
                  solution: `$$\\displaylines{\\textbf{v}(t) = (1 - \\cos t)\\,\\mathbf{i} + \\sin t\\,\\mathbf{j} + 2\\cos \\frac{t}{2}\\,\\mathbf{k}\\\\ \\textbf{a}(t) = \\sin t\\,\\mathbf{i} + \\cos t\\,\\mathbf{j} - \\sin \\frac{t}{2}\\,\\mathbf{k}\\\\ v(t) = \\left(1 - 2 \\cos t  + \\cos^2 t + \\sin^2 t + 4 \\cos^2 \\frac{t}{2}\\right)^{1/2}\\\\ = 2}$$`,
                  date: "2024-01-27"
                },
                {
                  id: 5,
                  number: "14.7.5",
                  content: `In each of Exercises 1 through 6, $\\textbf{r}(t)$ denotes the position vector at time $t$ for a particle moving on a space curve. Determine the velocity $\\textbf{v}(t)$ and acceleration $\\textbf{a}(t)$ in terms of $\\mathbf{i}, \\mathbf{j}, \\mathbf{k}$; also, compute the speed $v(t)$.\n\n$$\\textbf{r}(t) = 3t^2\\mathbf{i} + 2t^3\\mathbf{j}$$`,
                  hint: ``,
                  solution: `$$\\displaylines{\\mathbf{v}(t) = 6t\\,\\mathbf{i} + 6t^2\\,\\mathbf{j} +3\\,\\mathbf{k}\\\\ \\mathbf{a} = 6\\,\\mathbf{i} + 12t\\,\\mathbf{j}\\\\ v(t) = 3 + 6t^2}$$`,
                  date: "2024-01-27"
                },
                {
                  id: 6,
                  number: "14.7.6",
                  content: `In each of Exercises 1 through 6, $\\textbf{r}(t)$ denotes the position vector at time $t$ for a particle moving on a space curve. Determine the velocity $\\textbf{v}(t)$ and acceleration $\\textbf{a}(t)$ in terms of $\\mathbf{i}, \\mathbf{j}, \\mathbf{k}$; also, compute the speed $v(t)$.\n\n$$\\textbf{r}(t) = t\\mathbf{i} + \\sin t\\mathbf{j} + (1 - \\cos t)\\,\\mathbf{k}$$`,
                  hint: ``,
                  solution: `$$\\displaylines{\\mathbf{v}(t) = \\mathbf{i} + \\cos t\\,\\mathbf{j} + \\sin t \\,\\mathbf{k}\\\\ \\mathbf{a}(t) = -\\sin t\\,\\mathbf{j} + \\cos t\\,\\mathbf{k}\\\\ v(t) = \\sqrt{2}}$$`,
                  date: "2024-01-27"
                },
                {
                  id: 7,
                  number: "14.7.7",
                  content: `Consider the helix described by the vector equation $\\textbf{r}(t) = a\\cos \\omega t\\mathbf{i} + a\\sin \\omega t\\mathbf{j} + b\\omega t\\,\\mathbf{k}$, where $\\omega$ is a positive constant. Prove that the tangent line makes a constant angle with the $z$-axis and that the cosine of this angle is $b/\\sqrt{a^2 + b^2}$.`,
                  hint: ``,
                  solution: `First, we find the equation of the tangent vector $\\mathbf{v}(t) = \\mathbf{r}'(t)$:

$$\\mathbf{v}(t) = -a\\omega\\,\\sin \\omega t\\,\\mathbf{i} + a\\omega \\cos \\omega t\\,\\mathbf{j} + b \\omega\\,\\mathbf{k}$$
Then, we take its dot product with $\\mathbf{k}$, which is equal to $b\\,\\omega$. Written another way,

$$b\\,\\omega = \\|\\mathbf{v}(t)\\|\\,\\|\\mathbf{k}\\|\\cos \\theta$$
Where $\\theta$ is the angle between $\\mathbf{v}$ and $\\mathbf{k}$. Evaluating the norm of $\\mathbf{v}(t)$ gives us $\\omega\\,\\left(a^2 + b^2\\right)^{1/2}$, and of course the norm of the unit vector $\\mathbf{k}$ is 1. Combining these terms, we show that the angle $\\theta$ is constant, with 

$$\\cos \\theta = \\frac{b}{\\sqrt{a^2 + b^2}}$$ `,
                  date: "2024-01-27"
                },
                {
                  id: 8,
                  number: "14.7.8",
                  content: `Referring to the helix in Exercise 7, prove that the velocity $v$ and acceleration $a$ are vectors of constant length, and that:\n $$\\frac{\\|\\mathbf{v} \\times \\mathbf{a}\\|}{\\|\\mathbf{v}\\|^3} = \\frac{a}{a^2 + b^2}$$`,
                  hint: ``,
                  solution: `Recall from exercise 7 that 

$$\\mathbf{v}(t) = -a\\omega\\,\\sin \\omega t\\,\\mathbf{i} + a\\omega \\cos \\omega t\\,\\mathbf{j} + b \\omega\\,\\mathbf{k}$$
Taking its derivative, we get 

$$\\mathbf{a}(t) = -a\\omega^2\\,\\cos \\omega t\\,\\mathbf{i} - a\\omega^2 \\sin \\omega t\\,\\mathbf{j}$$
Taking its norm, we see that $\\|\\mathbf{a}\\| = \\left[a^2\\omega^4\\left(\\cos^2 \\omega t + \\sin^2 \\omega t\\right)\\right]^{1/2} = a\\omega^2$. And we know from exercise 7 that $\\mathbf{v}$ is of constant length $\\omega \\sqrt{a^2 + b^2}$. This proves that $\\mathbf{v}$ and $\\mathbf{a}$ are of constant length.

To prove that 
$$\\frac{\\|\\mathbf{v} \\times \\mathbf{a}\\|}{\\|\\mathbf{v}\\|^3} = \\frac{a}{a^2 + b^2}$$
we first calculate $\\mathbf{v} \\times \\mathbf{a}$:

$$\\mathbf{v} \\times \\mathbf{a} = \\left(ab\\omega^3 \\sin \\omega t\\right)\\,\\mathbf{i} - \\left(ab\\omega^3 \\cos \\omega t\\right)\\,\\mathbf{j} + \\left(a^2\\omega^3 \\sin^2 \\omega t + a^2\\omega^3 \\cos^2 \\omega t\\right)\\,\\mathbf{k}$$
Taking its norm, we get

$$\\displaylines{\\|\\mathbf{v} \\times \\mathbf{a}\\| = \\left(a^2b^2\\omega^6 + a^4\\omega^6\\right)^{1/2}\\\\ = a\\omega^3\\sqrt{a^2 + b^2}}$$
Combining this result with $\\|\\mathbf{v}\\|^3 = \\omega^3\\left(a^2 + b^2\\right)^{3/2}$, we find that 

$$\\frac{\\|\\mathbf{v} \\times \\mathbf{a}\\|}{\\|\\mathbf{v}\\|^3} = \\frac{a}{a^2 + b^2}$$`,
                  date: "2024-01-27"
                },
                {
                  id: 9,
                  number: "14.7.9",
                  content: `Referring to Exercise 7, let $\\mathbf{u}(t)$ denote the unit vector $\\mathbf{u}(t) = \\sin \\omega t\\mathbf{i} - \\cos \\omega t\\mathbf{j}$. Prove that there are constants $A$ and $B$ such that $\\mathbf{v} \\times \\mathbf{a} = A\\mathbf{u}(t) + B\\,\\mathbf{k}$, and express $A$ and $B$ in terms of $a$, $b$, and $\\omega$.`,
                  hint: `Recall from exercise 8:
                  
$$\\mathbf{v} \\times \\mathbf{a} = \\left(ab\\omega^3 \\sin \\omega t\\right)\\,\\mathbf{i} - \\left(ab\\omega^3 \\cos \\omega t\\right)\\,\\mathbf{j} + a^2\\omega^3\\left(\\sin^2 \\omega t + \\cos^2 \\omega t\\right)\\,\\mathbf{k}$$`,
                  solution: `We can express the cross product $\\mathbf{v} \\times \\mathbf{a}$ as the linear combination $A\\mathbf{u}(t) + B\\mathbf{k}$, where $$A = ab\\omega^3, \\quad B = a^2\\omega^3$$`,
                  date: "2024-01-27"
                },
                {
                  id: 10,
                  number: "14.7.10",
                  content: `Prove that for any motion the dot product of the velocity and acceleration is half the derivative of the square of the speed:\n$$\\textbf{v}(t) \\cdot \\textbf{a}(t) = \\frac{1}{2}\\frac{d}{dt}v^2(t)$$`,
                  hint: `Recall that $v^2(t) = \\mathbf{v}(t) \\cdot \\mathbf{v}(t)$. Then, apply the dot product rule for vector derivatives.`,
                  solution: `$$\\displaylines{\\mathbf{v}(t) \\cdot \\mathbf{a}(t)\\ = \\frac{1}{2}\\left(\\mathbf{v}(t) \\cdot \\mathbf{v}(t)\\right)'\\\\ = \\frac{1}{2}\\frac{d}{dt}v^2(t) \\quad \\blacksquare}$$`,
                  date: "2024-01-27"
                },
                {
                  id: 11,
                  number: "14.7.11",
                  content: `Let $\\mathbf{c}$ be a fixed unit vector. A particle moves in space in such a way that its position vector $\\textbf{r}(t)$ satisfies the equation $\\textbf{r}(t) \\cdot \\mathbf{c} = e^{2t}$ for all $t$, and its velocity vector $\\textbf{v}(t)$ makes a constant angle $\\theta$ with $\\mathbf{c}$, where $0 < \\theta < \\frac{\\pi}{2}$.\n\n(a) Prove that the speed at time $t$ is $2e^{2t}/\\cos \\theta$.\n(b) Compute the dot product $\\textbf{a}(t) \\cdot \\textbf{v}(t)$ in terms of $t$ and $\\theta$.`,
                  hint: `(a) Note that speed is the norm of the velocity vector, and that 

$$\\cos \\theta = \\frac{\\mathbf{v}(t) \\cdot \\mathbf{c}}{\\|\\mathbf{v}(t)\\|\\|\\mathbf{c}\\|}$$
(b) Note that if we differentiate the dot product $\\mathbf{v} \\cdot \\mathbf{v}$ we get: $$\\displaylines{\\left(\\mathbf{v} \\cdot \\mathbf{v}\\right)' = \\mathbf{v}' \\cdot \\mathbf{v} + \\mathbf{v} \\cdot \\mathbf{v}'\\\\ = 2\\ \\mathbf{a} \\cdot \\mathbf{v}}$$`,
                  solution: `(a) Differentiating both sides of the equation $\\mathbf{r}(t) \\cdot \\mathbf{c} = e^{2t}$, we get: 

$$\\mathbf{v}(t) \\cdot \\mathbf{c} = 2\\ e^{2t}$$
Written another way,

$$\\|\\mathbf{v}(t)\\|\\|\\mathbf{c}\\|\\cos \\theta = 2\\ e^{2t}$$
And since we know $\\mathbf{c}$ is of unit length, speed $\\|\\mathbf{v}(t)\\|$ is 

$$\\|\\mathbf{v}(t)\\| = \\frac{2e^{2t}}{\\cos \\theta}$$

(b) First, we note that $\\|\\mathbf{v}(t)\\|^2 = \\mathbf{v}(t) \\cdot \\mathbf{v}(t) = \\frac{4e^{4t}}{\\cos^2 t}$. Then, differentiating with respect to $t$ gives us: 

$$\\displaylines{2\\,\\mathbf{a}(t) \\cdot \\mathbf{v}(t) = \\frac{16\\,e^{4t}}{\\cos^2 \\theta}}$$
Or in other words: 
$$\\displaylines{\\mathbf{a}(t) \\cdot \\mathbf{v}(t) = \\frac{8\\,e^{4t}}{\\cos^2 \\theta}}$$`,
                  date: "2024-01-27"
                },
                {
                  id: 12,
                  number: "14.7.12",
                  content: `The identity $\\cosh^2 \\theta - \\sinh^2 \\theta = 1$ for hyperbolic functions suggests that the hyperbola $x^2/a^2 - y^2/b^2 = 1$ may be represented by the parametric equations $x = a\\cosh \\theta$, $y = b\\sinh \\theta$, or what amounts to the same thing, by the vector equation $r = a\\cosh \\theta\\mathbf{i} + b\\sinh \\theta\\mathbf{j}$. When $a = b = 1$, the parameter $\\theta$ may be given a geometric interpretation analogous to that which holds between $\\theta$, $\\sin \\theta$, and $\\cos \\theta$ in the unit circle shown in Figure 14.7(a). Figure 14.7(b) shows one branch of the hyperbola $x^2 - y^2 = 1$. If the point $P$ has coordinates $x = \\cosh \\theta$ and $y = \\sinh \\theta$, prove that $\\theta$ equals twice the area of the sector $OAP$ shaded in the figure.\n[Hint: Let $A(\\theta)$ denote the area of sector $OAP$. Show that $$A(\\theta) = \\frac{1}{2}\\cosh \\theta \\sinh \\theta - \\int_1^{\\cosh \\theta} \\sqrt{x^2 - 1}\\,dx$$Differentiate to get $A'(\\theta) = \\frac{1}{2}$.]`,
                  hint: ``,
                  solution: `Since the curve in question is a hyperbola, we know that each $P$ on the curve can be written as $(x, y) = \\left(\\cosh \\theta, \\sinh \\theta \\right)$. As such, the area of the right triangle with vertices $O, P, (x, 0)$ is $\\frac{1}{2}bh = \\frac{1}{2} \\cosh \\theta \\sinh \\theta$. Now, to find the area of the sector $OAP$, we must subtract from the right triangle $O, P, (x, 0)$ the area under the curve $y = \\sqrt{x^2 - 1}$ from $x = A$ to $x = \\cosh \\theta$. But $A$ is a point on the hyperbola desctibed by $x^2 - y^2 = 1$, since $A$ touches the $x$-axis, thus $A$ must be $(1, 0)$. This difference, written as a function of $\\theta$ is 

$$A(\\theta) = \\frac{1}{2} \\cosh \\theta \\sinh \\theta - \\int_1^{\\cosh \\theta} \\sqrt{x^2 - 1}\\, dx$$
Taking the derivative with respect to $\\theta$ gives us: 

$$\\displaylines{A'(\\theta) = \\frac{1}{2}\\left(\\sinh^2 \\theta + \\cosh^2 \\theta\\right) - \\left(\\sinh \\theta \\sqrt{\\cosh^2 \\theta - 1}\\right)\\\\ = \\frac{1}{2}\\left(\\sinh^2 \\theta + \\cosh^2 \\theta\\right) - \\left(\\sinh \\theta \\sqrt{\\sinh^2 \\theta}\\right)\\\\ = \\frac{1}{2}\\left(\\cosh^2 \\theta- \\sinh^2 \\theta\\right)\\\\ = \\frac{1}{2}}$$
This implies, however, that the area $A(\\theta)$ is 

$$A(\\theta) = \\int_0^{\\theta}\\frac{1}{2}\\,dt = \\frac{\\theta}{2}$$
Or in other words, that the angle $\\theta$ is twice the area $A(\\theta)$ of the sector $OAP$. This completes the proof.`,
                  date: "2024-01-27"
                },
                {
                  id: 13,
                  number: "14.7.13",
                  content: `A particle moves along a hyperbola according to the equation 

$$\\textbf{r}(t) = a\\cosh \\omega t\\,\\mathbf{i} + b\\sinh \\omega t\\,\\mathbf{j}$$
where $\\omega$ is a constant. Prove that the acceleration is centrifugal.`,
                  hint: `By definition, acceleration is centrifugal if the position vector and acceleration vector have the same direction (ie, away from the center of the hyperbola at the origin).`,
                  solution: `We wish to show that for some positive scalar $c$, that $\\mathbf{a} = c\\,\\mathbf{r}$. Differentiating with respect to $t$, we get 

$$\\displaylines{\\mathbf{v}(t) = \\omega a\\,\\sinh \\omega t\\,\\mathbf{i} + \\omega b\\,\\cosh \\omega t\\,\\mathbf{j} \\\\\\mathbf{a}(t) = \\omega^2 a\\,\\cosh \\omega t\\,\\mathbf{i} + \\omega^2 b\\,\\sinh \\omega t\\,\\mathbf{j}\\\\ = \\omega^2\\, \\mathbf{r}{(t)}}$$`,
                  date: "2024-01-27"
                },
                {
                  id: 14,
                  number: "14.7.14",
                  content: `Prove that the tangent line at a point $X$ of a parabola bisects the angle between the line joining $X$ to the focus and the line through $X$ parallel to the axis. This gives the reflection property of the parabola. (See Figure 14.3.)`,
                  hint: ``,
                  solution: `Let the focus $F = 0$, then $X - F = X$. If $\\mathbf{u}$ is a unit vector with the same direction as $X$, then we can define $X$ as $d\\mathbf{u}$ where $d = \\|X\\|$. Now, let $P$ be a point on the vertical directrix line $L$, with $X - P$ parallel to the axis of the parabola (i.e., the $x$-axis). By definition, $\\|X - P\\|$ must be $d$. In other words, we can rewrite
$$
X = P + d\\,\\mathbf{i},
$$
Taking the derivative of $X$ with respect to $t$ using both definitions, we get

$$
X' = d'\\,\\mathbf{u} + d\\,\\mathbf{u}'; \\quad
X' = P' + d'\\,\\mathbf{i},
$$(since $\\mathbf{i}' = 0)$. 

Taking the dot products with $\\mathbf{u}$ and $\\mathbf{i}$, respectively, and recalling that $\\mathbf{u}'\\cdot\\mathbf{u} = 0$ and $\\mathbf{i}'\\cdot\\mathbf{i} = 0$ (since $\\mathbf{u}$ and $\\mathbf{i}$ are of constant length), we get:

$$
X'\\cdot \\mathbf{u} = d'; \\quad X'\\cdot \\mathbf{i} = P'\\cdot \\mathbf{i} + d'.
$$
But $P'$ must be perpendicular to $\\mathbf{i}$ since $P$ can only ever move vertically. Thus, $P'\\cdot\\, \\mathbf{i} = 0$, so that
$$
X'\\cdot \\mathbf{u} = X'\\cdot \\mathbf{i} = d'.
$$
Assuming that the directrix line is to the left of the parabola, this means that the angles between $X$ and $\\mathbf{i}$, $X'$ and $\\mathbf{i}$, and $X'$ and $\\mathbf{u}$ are all such that $0 < \\theta < \\frac{\\pi}{2}$. Thus, the cosines determined by the above dot products are unique.

And since $\\mathbf{u} \\neq \\mathbf{i}$, it follows that the tangent line (with direction $X'$) bisects the angle between the line segment from the focus to $X$ (which has direction $\\mathbf{u}$) and the horizontal line through $X$ (which has direction $\\mathbf{i}$), thus proving the reflection property of the parabola.`
,
                  date: "2024-01-27"
                },
                {
                  id: 15,
                  number: "14.7.15",
                  content: `A particle of mass 1 moves in a plane according to the equation $\\textbf{r}(t) = x(t)\\mathbf{i} + y(t)\\mathbf{j}$. It is attracted toward the origin by a force whose magnitude is four times its distance from the origin. At time $t = 0$, the initial position is $r(0) = 4\\mathbf{i}$ and the initial velocity is $v(0) = 6\\mathbf{j}$.\n\n(a) Determine the components $x(t)$ and $y(t)$ explicitly in terms of $t$.\n(b) The path of the particle is a conic section. Find a Cartesian equation for this conic, sketch the conic, and indicate the direction of motion along the curve.`,
                  hint: ``,
                  solution: ``,
                  date: "2024-01-27"
                },
                {
                  id: 16,
                  number: "14.7.16",
                  content: `A particle moves along the parabola $x^2 + c(y - x) = 0$ in such a way that the horizontal and vertical components of the acceleration vector are equal. If it takes $T$ units of time to go from the point $(c, 0)$ to the point $(0, 0)$, how much time will it require to go from $(c, 0)$ to the halfway point $(c/2, c/4)$?`,
                  hint: ``,
                  solution: ``,
                  date: "2024-01-27"
                },
                {
                  id: 17,
                  number: "14.7.17",
                  content: `Suppose a curve $C$ is described by two equivalent functions $X$ and $Y$, where $Y(t) = X[\\varphi(t)]$. Prove that at each point of $C$ the velocity vectors associated with $X$ and $Y$ are parallel, but that the corresponding acceleration vectors need not be parallel.`,
                  hint: ``,
                  solution: ``,
                  date: "2024-01-27"
                }
              ]
            },
          ]
        },
      ]
    },
    // {
    //   id: 2,
    //   title: "Linear Algebra Done Right",
    //   author: "Sheldon Axler",
    //   edition: "Third Edition",
    //   year: "2015",
    //   chapters: []  // We can fill this in later
    // },
    // Add more textbooks as needed
  ];